export const VERSION='2.0.0';
export const WORLD={w:1600,h:900,groundStep:2,gravity:255,windAccel:18,tankW:54,tankH:30,turnSeconds:35};
export const AMMO={
 standard:{id:'standard',name:'Звичайний',icon:'💣',count:Infinity,damage:35,radius:70,crater:38,speed:7.2,desc:'Надійний збалансований снаряд.'},
 heavy:{id:'heavy',name:'Важкий',icon:'🧨',count:2,damage:52,radius:95,crater:58,speed:5.7,desc:'Велика шкода і воронка, але коротша дальність.'},
 cluster:{id:'cluster',name:'Касета',icon:'🎆',count:1,damage:18,radius:42,crater:22,speed:6.8,desc:'Розпадається на п’ять бомб біля вершини польоту.'},
 napalm:{id:'napalm',name:'Напалм',icon:'🔥',count:1,damage:25,radius:72,crater:28,speed:6.6,desc:'Залишає вогонь на два ходи.'},
 drill:{id:'drill',name:'Бур',icon:'🌀',count:1,damage:45,radius:65,crater:50,speed:7,desc:'Проникає в землю перед вибухом.'},
 ricochet:{id:'ricochet',name:'Рикошет',icon:'↗️',count:1,damage:38,radius:66,crater:34,speed:7.5,desc:'Один раз відскакує від поверхні.'},
 mine:{id:'mine',name:'Міна',icon:'⚫',count:1,damage:48,radius:78,crater:42,speed:5.5,desc:'Залишається на землі й реагує на танк.'},
 emp:{id:'emp',name:'EMP',icon:'⚡',count:1,damage:18,radius:90,crater:18,speed:7,desc:'Знімає щит і зменшує пальне наступного ходу.'},
 repair:{id:'repair',name:'Ремонт',icon:'💚',count:1,damage:-32,radius:0,crater:0,speed:0,desc:'Одразу ремонтує ваш танк.'},
 airstrike:{id:'airstrike',name:'Авіаудар',icon:'🚀',count:1,damage:22,radius:48,crater:25,speed:7,desc:'Після наведення зверху падає серія ракет.'}
};
export const AMMO_ORDER=Object.keys(AMMO);

export function hashSeed(text){let h=2166136261>>>0;for(const c of String(text)){h^=c.charCodeAt(0);h=Math.imul(h,16777619)}return h>>>0}
export function rand(state){let x=state.rng>>>0;x^=x<<13;x^=x>>>17;x^=x<<5;state.rng=x>>>0;return(state.rng>>>0)/4294967296}
export function randRange(state,a,b){return a+(b-a)*rand(state)}
export function makeTerrain(seed){const temp={rng:seed||1};const n=Math.ceil(WORLD.w/WORLD.groundStep)+1;const out=[];const phase=randRange(temp,0,Math.PI*2);const phase2=randRange(temp,0,Math.PI*2);for(let i=0;i<n;i++){const x=i*WORLD.groundStep;const base=650+72*Math.sin(x/190+phase)+42*Math.sin(x/73+phase2)+18*Math.sin(x/31);const edge=80*Math.pow(Math.abs(x-WORLD.w/2)/(WORLD.w/2),1.7);out.push(Math.max(430,Math.min(790,base+edge)))}for(let k=0;k<4;k++){for(let i=1;i<n-1;i++)out[i]=(out[i-1]+out[i]*2+out[i+1])/4}return out}
export function terrainY(state,x){const p=Math.max(0,Math.min(state.terrain.length-1,x/WORLD.groundStep));const a=Math.floor(p),b=Math.min(state.terrain.length-1,a+1),t=p-a;return state.terrain[a]*(1-t)+state.terrain[b]*t}
export function terrainSlope(state,x){return(terrainY(state,x+12)-terrainY(state,x-12))/24}
export function settleTank(state,tank){tank.x=Math.max(35,Math.min(WORLD.w-35,tank.x));tank.y=terrainY(state,tank.x)-WORLD.tankH/2-3;tank.rotation=Math.atan(terrainSlope(state,tank.x))}
function defaultInventory(){const inv={};for(const id of AMMO_ORDER)inv[id]=AMMO[id].count;return inv}
export function createState(seed=Date.now(),names=['Гравець','Суперник']){const s={version:VERSION,seed:seed>>>0,rng:(seed^0x9e3779b9)>>>0,terrain:makeTerrain(seed>>>0),tanks:[{id:0,name:names[0]||'Гравець',x:210,y:0,hp:100,shield:0,angle:45,power:65,fuel:100,empDrain:0,ammo:defaultInventory(),selected:'standard',alive:true},{id:1,name:names[1]||'Суперник',x:1390,y:0,hp:100,shield:0,angle:135,power:65,fuel:100,empDrain:0,ammo:defaultInventory(),selected:'standard',alive:true}],turn:0,turnNumber:1,turnEndsAt:0,wind:0,phase:'aim',projectiles:[],particles:[],mines:[],fires:[],airdrop:null,plane:null,events:[],winner:null,shotSerial:0};s.wind=Math.round(randRange(s,-6,6));s.tanks.forEach(t=>settleTank(s,t));return s}
export function cloneState(s){return JSON.parse(JSON.stringify(s))}
export function packState(s){return JSON.stringify(s)}
export function unpackState(v){const s=typeof v==='string'?JSON.parse(v):v;if(!s||s.version!==VERSION||!Array.isArray(s.terrain)||!Array.isArray(s.tanks))throw new Error('Invalid snapshot');return s}
export function ammoAvailable(t,id){return id==='standard'||(Number.isFinite(t.ammo[id])&&t.ammo[id]>0)}
export function selectAmmo(state,player,id){if(!AMMO[id]||state.turn!==player||!ammoAvailable(state.tanks[player],id))return false;state.tanks[player].selected=id;return true}
export function canMove(state,player,dir){if(state.phase!=='aim'||state.turn!==player||![-1,1].includes(dir))return false;const t=state.tanks[player];if(t.fuel<=0||!t.alive)return false;const nx=t.x+dir*5;if(nx<35||nx>WORLD.w-35)return false;const dy=Math.abs(terrainY(state,nx+dir*18)-terrainY(state,nx-dir*18));if(dy>40)return false;const other=state.tanks[1-player];if(Math.abs(nx-other.x)<WORLD.tankW+10)return false;return true}
export function moveTank(state,player,dir,dt){if(!canMove(state,player,dir))return 0;const t=state.tanks[player];const maxDx=Math.min(105*dt,t.fuel/0.72);const before=t.x;t.x+=dir*maxDx;settleTank(state,t);t.fuel=Math.max(0,t.fuel-Math.abs(t.x-before)*0.72);pickupAirdrop(state,t);checkMines(state,t);return t.x-before}
export function muzzle(tank){const r=tank.angle*Math.PI/180;return{x:tank.x+Math.cos(r)*42,y:tank.y-Math.sin(r)*42}}
export function initialVelocity(tank,ammo){const a=AMMO[ammo]||AMMO.standard;const r=tank.angle*Math.PI/180;const v=tank.power*a.speed;return{vx:Math.cos(r)*v,vy:-Math.sin(r)*v}}
export function simulateTrajectory(state,tank,ammo=tank.selected,max=240,dt=.045){const p=muzzle(tank),v=initialVelocity(tank,ammo),points=[];let x=p.x,y=p.y,vx=v.vx,vy=v.vy,bounced=false;for(let i=0;i<max;i++){vx+=state.wind*WORLD.windAccel*dt;vy+=WORLD.gravity*dt;x+=vx*dt;y+=vy*dt;if(i%3===0)points.push({x,y});if(x<0||x>WORLD.w||y>WORLD.h)break;if(y>=terrainY(state,x)){if(ammo==='ricochet'&&!bounced){bounced=true;y=terrainY(state,x)-4;vy=-Math.abs(vy)*.6;vx*=.82}else break}}return points}
export function predictedImpact(state,tank,ammo=tank.selected){const pts=simulateTrajectory(state,tank,ammo,320,.035);return pts[pts.length-1]||muzzle(tank)}
export function fire(state,player){if(state.phase!=='aim'||state.turn!==player||state.winner!==null)return false;const t=state.tanks[player],id=t.selected;if(!ammoAvailable(t,id))return false;if(id==='repair'){if(id!=='standard')t.ammo[id]--;t.hp=Math.min(100,t.hp+32);state.events.push({type:'heal',player,amount:32});state.phase='resolving';state.resolveAt=performanceNow()+850;return true}if(id!=='standard')t.ammo[id]--;const m=muzzle(t),v=initialVelocity(t,id);state.projectiles.push({id:++state.shotSerial,owner:player,ammo:id,x:m.x,y:m.y,vx:v.vx,vy:v.vy,age:0,bounced:false,split:false,dead:false});state.phase='projectile';state.events.push({type:'fire',player,ammo:id});return true}
function performanceNow(){return typeof performance!=='undefined'?performance.now():Date.now()}
export function deformTerrain(state,x,radius,depth){const a=Math.max(0,Math.floor((x-radius)/WORLD.groundStep)),b=Math.min(state.terrain.length-1,Math.ceil((x+radius)/WORLD.groundStep));for(let i=a;i<=b;i++){const px=i*WORLD.groundStep,d=Math.abs(px-x);if(d<=radius){const delta=depth*Math.sqrt(Math.max(0,1-(d*d)/(radius*radius)));state.terrain[i]=Math.min(WORLD.h-8,state.terrain[i]+delta)}}}
export function applyBlast(state,x,y,ammoId,owner,scale=1){const a=AMMO[ammoId]||AMMO.standard;const radius=a.radius*scale;if(a.crater)deformTerrain(state,x,a.radius*scale,a.crater*scale);for(const t of state.tanks){const d=Math.hypot(t.x-x,t.y-y);if(d<radius+35){let dmg=Math.max(0,a.damage*(1-d/(radius+35))*scale);if(ammoId==='emp'){t.shield=0;t.empDrain=Math.max(t.empDrain,45)}if(dmg>0&&t.shield>0){const absorbed=Math.min(t.shield,dmg*.7);t.shield-=absorbed;dmg-=absorbed}t.hp=Math.max(0,t.hp-dmg);if(t.hp<=0){t.alive=false;state.winner=1-t.id}}}if(ammoId==='napalm')state.fires.push({x,radius:85,turns:2,owner});state.events.push({type:'explode',x,y,ammo:ammoId,owner});state.tanks.forEach(t=>settleTank(state,t))}
function impactProjectile(state,p){const id=p.ammo;if(id==='mine'){p.dead=true;state.mines.push({x:p.x,y:terrainY(state,p.x)-8,owner:p.owner,armedTurn:state.turnNumber+1});state.events.push({type:'mine',x:p.x});return}if(id==='drill'){p.y=Math.min(WORLD.h-20,p.y+42)}if(id==='airstrike'){p.dead=true;const targetX=p.x;state.airstrike={owner:p.owner,targetX,t:0,rockets:5};state.events.push({type:'airstrike',x:targetX});return}p.dead=true;applyBlast(state,p.x,p.y,id,p.owner)}
export function stepState(state,dt){if(state.winner!==null)return;stepPlaneDrop(state,dt);for(const p of state.projectiles){if(p.dead)continue;p.age+=dt;p.vx+=state.wind*WORLD.windAccel*dt;p.vy+=WORLD.gravity*dt;p.x+=p.vx*dt;p.y+=p.vy*dt;if(p.ammo==='cluster'&&!p.split&&p.age>.45&&p.vy>0){p.dead=true;p.split=true;for(let i=-2;i<=2;i++)state.projectiles.push({id:++state.shotSerial,owner:p.owner,ammo:'standard',x:p.x+i*4,y:p.y,vx:p.vx+i*42,vy:p.vy-40-Math.abs(i)*8,age:0,bounced:false,split:true,dead:false,mini:true})}if(p.x<0||p.x>WORLD.w||p.y>WORLD.h){p.dead=true;continue}if(p.y>=terrainY(state,p.x)){if(p.ammo==='ricochet'&&!p.bounced&&Math.abs(p.vy)>50){p.bounced=true;p.y=terrainY(state,p.x)-5;p.vy=-Math.abs(p.vy)*.58;p.vx*=.82}else impactProjectile(state,p)}}state.projectiles=state.projectiles.filter(p=>!p.dead);if(state.airstrike){state.airstrike.t+=dt;if(state.airstrike.rockets>0&&state.airstrike.t>.22){state.airstrike.t=0;const n=state.airstrike.rockets--;const x=state.airstrike.targetX+(n-2)*34;state.projectiles.push({id:++state.shotSerial,owner:state.airstrike.owner,ammo:'standard',x,y:30,vx:randRange(state,-12,12),vy:160,age:0,bounced:false,split:true,dead:false,air:true})}if(state.airstrike.rockets<=0&&state.projectiles.length===0)state.airstrike=null}if(state.phase==='projectile'&&state.projectiles.length===0&&!state.airstrike){state.phase='resolving';state.resolveAt=performanceNow()+900}if(state.phase==='resolving'&&performanceNow()>=state.resolveAt)advanceTurn(state)}
export function advanceTurn(state){for(const f of state.fires){for(const t of state.tanks){if(Math.abs(t.x-f.x)<f.radius){t.hp=Math.max(0,t.hp-8);state.events.push({type:'burn',player:t.id,amount:8});if(t.hp<=0){t.alive=false;state.winner=1-t.id}}}f.turns--}state.fires=state.fires.filter(f=>f.turns>0);state.turn=1-state.turn;state.turnNumber++;const t=state.tanks[state.turn];t.fuel=Math.max(30,100-t.empDrain);t.empDrain=0;state.wind=Math.round(randRange(state,-6,6));state.phase='aim';state.turnEndsAt=performanceNow()+WORLD.turnSeconds*1000;maybeSpawnAirdrop(state);state.events.push({type:'turn',player:state.turn})}
export function maybeSpawnAirdrop(state){if(state.airdrop||state.plane||state.turnNumber<3)return;if(rand(state)<.31){const fromLeft=rand(state)>.5;state.plane={x:fromLeft?-120:WORLD.w+120,y:145,vx:fromLeft?190:-190,dropX:randRange(state,420,WORLD.w-420),dropped:false};state.events.push({type:'plane'})}}
function stepPlaneDrop(state,dt){if(state.plane){state.plane.x+=state.plane.vx*dt;if(!state.plane.dropped&&((state.plane.vx>0&&state.plane.x>=state.plane.dropX)||(state.plane.vx<0&&state.plane.x<=state.plane.dropX))){state.plane.dropped=true;state.airdrop={x:state.plane.x,y:state.plane.y+25,vy:20,landed:false,turns:4,loot:null}}if(state.plane.x<-180||state.plane.x>WORLD.w+180)state.plane=null}if(state.airdrop&&!state.airdrop.landed){state.airdrop.vy+=68*dt;state.airdrop.y+=state.airdrop.vy*dt;const gy=terrainY(state,state.airdrop.x)-16;if(state.airdrop.y>=gy){state.airdrop.y=gy;state.airdrop.landed=true;state.events.push({type:'dropLand',x:state.airdrop.x})}}if(state.airdrop?.landed){state.tanks.forEach(t=>pickupAirdrop(state,t))}}
export function pickupAirdrop(state,tank){const d=state.airdrop;if(!d||!d.landed||Math.abs(tank.x-d.x)>50)return false;const roll=rand(state);let loot;if(roll<.2){tank.hp=Math.min(100,tank.hp+28);loot='Ремонт +28 HP'}else if(roll<.38){tank.shield=Math.min(45,tank.shield+30);loot='Щит +30'}else if(roll<.55){tank.fuel=Math.min(100,tank.fuel+55);loot='Пальне +55'}else{const rare=['heavy','cluster','napalm','drill','ricochet','mine','emp','repair','airstrike'][Math.floor(rand(state)*9)];tank.ammo[rare]=(tank.ammo[rare]||0)+1;loot=`${AMMO[rare].name} +1`}state.events.push({type:'loot',player:tank.id,loot});state.airdrop=null;return true}
export function checkMines(state,tank){for(const m of state.mines){if(state.turnNumber>=m.armedTurn&&m.owner!==tank.id&&Math.abs(m.x-tank.x)<58&&!m.dead){m.dead=true;applyBlast(state,m.x,m.y,'mine',m.owner)}}state.mines=state.mines.filter(m=>!m.dead)}
export function validateAction(state,player,action){if(!action||state.winner!==null)return false;if(action.type==='move')return state.turn===player&&state.phase==='aim'&&[-1,1].includes(action.dir)&&Number.isFinite(action.dt)&&action.dt>0&&action.dt<=.12;if(action.type==='aim')return state.turn===player&&state.phase==='aim'&&Number.isFinite(action.angle)&&action.angle>=5&&action.angle<=175&&Number.isFinite(action.power)&&action.power>=20&&action.power<=100;if(action.type==='ammo')return state.turn===player&&state.phase==='aim'&&AMMO[action.id]&&ammoAvailable(state.tanks[player],action.id);if(action.type==='fire')return state.turn===player&&state.phase==='aim';return false}
export function applyAction(state,player,action){if(!validateAction(state,player,action))return false;if(action.type==='move')moveTank(state,player,action.dir,action.dt);else if(action.type==='aim'){state.tanks[player].angle=action.angle;state.tanks[player].power=action.power}else if(action.type==='ammo')selectAmmo(state,player,action.id);else if(action.type==='fire')fire(state,player);return true}
export function aiChoose(state,difficulty='normal'){const ai=state.tanks[1],target=state.tanks[0];let best={score:-Infinity,angle:135,power:65};const step=difficulty==='hard'?2:difficulty==='normal'?4:7;const noise=difficulty==='hard'?2:difficulty==='normal'?5:10;for(let angle=92;angle<=172;angle+=step){for(let power=30;power<=100;power+=step*2){const fake={...ai,angle,power};const hit=predictedImpact(state,fake,'standard');const dist=Math.abs(hit.x-target.x);const score=-dist-Math.abs(hit.y-target.y)*.15;if(score>best.score)best={score,angle,power}}}best.angle=Math.max(92,Math.min(175,best.angle+randRange(state,-noise,noise)));best.power=Math.max(25,Math.min(100,best.power+randRange(state,-noise,noise)));let selected='standard';if(ai.ammo.heavy>0&&Math.abs(target.x-ai.x)<650&&rand(state)<.25)selected='heavy';else if(ai.ammo.cluster>0&&rand(state)<.18)selected='cluster';else if(ai.ammo.emp>0&&target.shield>0)selected='emp';return{angle:best.angle,power:best.power,selected}}
