import{AMMO,AMMO_ORDER,WORLD,createState,stepState,moveTank,selectAmmo,fire,simulateTrajectory,terrainY,terrainSlope,applyAction,validateAction,aiChoose,packState,unpackState,randRange,advanceTurn}from'./core.js';

const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const screens={menu:$('#menu'),lobby:$('#lobby'),game:$('#game')};
const canvas=$('#gameCanvas'),ctx=canvas.getContext('2d',{alpha:false});
const settings=Object.assign({sound:true,vibration:true,contrast:false,reduced:false},JSON.parse(localStorage.getItem('ta-settings')||'{}'));
let state=null,mode='solo',localPlayer=0,isHost=false,room=null,peerId=null,connectedPeer=null,channels={},last=performance.now(),acc=0,lastSnapshot=0,aiPlan=null,aiAt=0,eventCursor=0,moveDir=0,toastTimer=0,paused=false,roomReady={host:false,guest:false},audioCtx=null;
let nickname=localStorage.getItem('ta-nickname')||'CREDESASQ';
$('#nickname').value=nickname;

function show(name){Object.values(screens).forEach(s=>s.classList.remove('active'));screens[name].classList.add('active')}
function saveSettings(){localStorage.setItem('ta-settings',JSON.stringify(settings));document.body.classList.toggle('reduced',settings.reduced)}
function toast(text){const el=$('#toast');el.textContent=text;el.classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>el.classList.remove('show'),1800)}
function log(text){const el=document.createElement('div');el.className='log-line';el.textContent=text;$('#combatLog').prepend(el);setTimeout(()=>el.remove(),5200)}
function beep(freq=180,dur=.12,type='sine',vol=.08){if(!settings.sound)return;try{audioCtx??=new AudioContext();const o=audioCtx.createOscillator(),g=audioCtx.createGain();o.type=type;o.frequency.value=freq;g.gain.setValueAtTime(vol,audioCtx.currentTime);g.gain.exponentialRampToValueAtTime(.001,audioCtx.currentTime+dur);o.connect(g).connect(audioCtx.destination);o.start();o.stop(audioCtx.currentTime+dur)}catch{}}
function vibrate(ms=35){if(settings.vibration&&navigator.vibrate)navigator.vibrate(ms)}
function now(){return performance.now()}
function freshTurnTimer(){if(state)state.turnEndsAt=now()+WORLD.turnSeconds*1000}

function startSolo(){mode='solo';localPlayer=0;isHost=true;nickname=$('#nickname').value.trim()||'Гравець';localStorage.setItem('ta-nickname',nickname);state=createState(Date.now(),[nickname,'BOT RANGER']);state.turnEndsAt=now()+WORLD.turnSeconds*1000;eventCursor=0;aiPlan=null;renderAmmo();syncHud();show('game');toast('Бій почався!')}
function startOnlineGame(snapshot){state=unpackState(snapshot);state.turnEndsAt=now()+WORLD.turnSeconds*1000;eventCursor=0;show('game');renderAmmo();syncHud();toast('Онлайн-бій почався!')}

function randomCode(){const chars='ABCDEFGHJKLMNPQRSTUVWXYZ23456789';let s='';crypto.getRandomValues(new Uint8Array(6)).forEach(v=>s+=chars[v%chars.length]);return s}
async function loadTrystero(){const urls=['https://esm.sh/@trystero-p2p/torrent@0.25.2?bundle','https://esm.sh/trystero@0.25.3/torrent?bundle'];let err;for(const u of urls){try{return await import(u)}catch(e){err=e}}throw err||new Error('P2P unavailable')}
function makeChannel(id){const raw=room.makeAction(id);if(Array.isArray(raw)){const[send,receive]=raw;return{send:(data,target)=>send(data,target),on:fn=>receive((data,id)=>fn(data,id))}}return{send:(data,target)=>raw.send(data,target?{target}:undefined),on:fn=>{raw.onMessage=(data,meta)=>fn(data,meta?.peerId)}}}
async function connectRoom(code,host){nickname=$('#nickname').value.trim()||'Гравець';localStorage.setItem('ta-nickname',nickname);mode='online';isHost=host;localPlayer=host?0:1;roomReady={host:false,guest:false};show('lobby');$('#lobbyCode').textContent=code;$('#hostName').textContent=host?nickname:'Очікування…';$('#guestName').textContent=host?'Очікування…':nickname;$('#lobbyStatus').textContent='Підключення до P2P-мережі…';$('#readyBtn').disabled=true;$('#readyBtn').textContent='Готовий';try{const{joinRoom}=await loadTrystero();room=joinRoom({appId:'tank-arena-online-v2',password:`TA-${code}`},code);channels.hello=makeChannel('hello');channels.ready=makeChannel('ready');channels.start=makeChannel('start');channels.action=makeChannel('action');channels.snapshot=makeChannel('snapshot');channels.notice=makeChannel('notice');channels.ping=makeChannel('ping');setupChannels(code);room.onPeerJoin?.(id=>{if(connectedPeer&&connectedPeer!==id){channels.notice.send({type:'full'},id);return}connectedPeer=id;peerId=id;$('#readyBtn').disabled=false;$('#lobbyStatus').textContent='Суперник підключився';channels.hello.send({nickname,host:isHost},id);beep(430,.12)});room.onPeerLeave?.(id=>{if(id===connectedPeer){connectedPeer=null;$('#networkLabel').textContent='● СУПЕРНИК ВИЙШОВ';$('#networkLabel').style.color='#ff685d';toast('Суперник відключився');if(!state){$('#lobbyStatus').textContent='Суперник відключився';$('#readyBtn').disabled=true}}});setTimeout(()=>channels.hello.send({nickname,host:isHost}),400);$('#lobbyStatus').textContent='Кімната створена. Очікуємо суперника…'}catch(e){console.error(e);$('#lobbyStatus').textContent='Не вдалося запустити онлайн. Перевірте інтернет/WebRTC.';toast('Помилка онлайн-з’єднання')}
}
function setupChannels(code){channels.hello.on((data,id)=>{if(data?.nickname){connectedPeer=id||connectedPeer;if(data.host){$('#hostName').textContent=data.nickname}else $('#guestName').textContent=data.nickname;$('#readyBtn').disabled=false;$('#lobbyStatus').textContent='Обидва гравці у кімнаті';channels.hello.send({nickname,host:isHost},id)}});channels.ready.on((data,id)=>{if(!data)return;roomReady[data.host?'host':'guest']=!!data.ready;if(data.host)$('#hostName').textContent=`${data.nickname}${data.ready?' ✓':''}`;else $('#guestName').textContent=`${data.nickname}${data.ready?' ✓':''}`;if(isHost&&roomReady.host&&roomReady.guest){const guest=$('#guestName').textContent.replace(' ✓','')||'Гість';state=createState(Date.now(),[nickname,guest]);state.turnEndsAt=now()+WORLD.turnSeconds*1000;channels.start.send(packState(state));startOnlineGame(packState(state))}});channels.start.on(snapshot=>{if(!isHost)startOnlineGame(snapshot)});channels.action.on((action,id)=>{if(!isHost||!state||id!==connectedPeer)return;if(applyAction(state,1,action)){if(action.type==='aim'||action.type==='ammo')sendSnapshot();if(action.type==='fire')sendSnapshot()}});channels.snapshot.on(snapshot=>{if(isHost)return;try{const incoming=unpackState(snapshot);incoming.turnEndsAt=state?.turn===incoming.turn&&state?.phase===incoming.phase?state.turnEndsAt:now()+WORLD.turnSeconds*1000;state=incoming;renderAmmo();syncHud()}catch(e){console.warn(e)}});channels.notice.on(data=>{if(data?.type==='full'){toast('Кімната вже заповнена');leaveOnline()}});channels.ping.on((data,id)=>channels.ping.send({reply:data?.t},id))}
function sendSnapshot(){if(isHost&&channels.snapshot&&connectedPeer&&state){channels.snapshot.send(packState(state),connectedPeer);lastSnapshot=now()}}
function leaveOnline(){try{room?.leave?.()}catch{}room=null;connectedPeer=null;channels={}}

function renderAmmo(){const bar=$('#ammoBar');bar.innerHTML='';if(!state)return;const t=state.tanks[localPlayer];for(const id of AMMO_ORDER){const a=AMMO[id],n=t.ammo[id];const btn=document.createElement('button');btn.className=`ammo ${t.selected===id?'selected':''}`;btn.title=a.desc;btn.disabled=!Number.isFinite(n)?false:n<=0;btn.innerHTML=`<span class="icon">${a.icon}</span><span><b>${a.name}</b><small>${a.damage<0?'лікування':`${a.damage} шк.`}</small></span><span class="count">${Number.isFinite(n)?`×${n}`:'∞'}</span>`;btn.onclick=()=>sendOrApply({type:'ammo',id});bar.append(btn)}}
function sendOrApply(action){if(!state||paused)return;if(mode==='online'&&!isHost){if(state.turn!==localPlayer||state.phase!=='aim')return;channels.action?.send(action,connectedPeer);if(action.type==='aim'){state.tanks[localPlayer].angle=action.angle;state.tanks[localPlayer].power=action.power}else if(action.type==='ammo'){state.tanks[localPlayer].selected=action.id;renderAmmo()}return}if(applyAction(state,localPlayer,action)){if(mode==='online')sendSnapshot();if(action.type==='ammo')renderAmmo()}}

function handleEvents(){
  if(!state)return;
  while(eventCursor<state.events.length){
    const e=state.events[eventCursor++];
    if(e.type==='fire'){
      beep(120,.16,'sawtooth',.12);vibrate(45);log(`${state.tanks[e.player].name}: ${AMMO[e.ammo].name}`);
    }else if(e.type==='explode'){
      beep(55,.35,'square',.16);vibrate([50,30,90]);log(`💥 Вибух ${AMMO[e.ammo]?.name||''}`);
    }else if(e.type==='loot'){
      toast(`🎁 ${state.tanks[e.player].name}: ${e.loot}`);log(`Аірдроп: ${e.loot}`);beep(660,.22);
    }else if(e.type==='turn'){
      toast(e.player===localPlayer?'Ваш хід!':'Хід суперника');renderAmmo();
    }else if(e.type==='heal'){
      toast(`+${e.amount} HP`);beep(520,.2);
    }else if(e.type==='plane'){
      log('🛩️ Аірдроп наближається');
    }else if(e.type==='burn'){
      log(`🔥 -${e.amount} HP`);
    }
  }
}
function syncHud(){if(!state)return;const[a,b]=state.tanks;$('#p1Name').textContent=a.name;$('#p2Name').textContent=b.name;$('#p1HpText').textContent=`${Math.ceil(a.hp)} HP${a.shield?` +${Math.ceil(a.shield)}🛡️`:''}`;$('#p2HpText').textContent=`${Math.ceil(b.hp)} HP${b.shield?` +${Math.ceil(b.shield)}🛡️`:''}`;$('#p1Hp').style.width=`${a.hp}%`;$('#p2Hp').style.width=`${b.hp}%`;const own=state.tanks[localPlayer];$('#fuelBar').style.width=`${own.fuel}%`;$('#angle').value=own.angle;$('#power').value=own.power;$('#angleOut').textContent=`${Math.round(own.angle)}°`;$('#powerOut').textContent=`${Math.round(own.power)}%`;$('#windLabel').textContent=`Вітер ${state.wind>0?'→':'←'} ${Math.abs(state.wind)}`;const mine=state.turn===localPlayer;$('#turnLabel').textContent=state.winner!==null?(state.winner===localPlayer?'ПЕРЕМОГА!':'ПОРАЗКА'):mine?'ВАШ ХІД':'ХІД СУПЕРНИКА';const left=Math.max(0,Math.ceil((state.turnEndsAt-now())/1000));$('#timerLabel').textContent=state.phase==='aim'?left:'•';$('#networkLabel').textContent=mode==='solo'?'● SOLO':connectedPeer?'● ONLINE':'● RECONNECT';$('#networkLabel').style.color=connectedPeer||mode==='solo'?'#62e891':'#ffb742';const enabled=mine&&state.phase==='aim'&&!paused;$('#fireBtn').disabled=!enabled;$('#angle').disabled=!enabled;$('#power').disabled=!enabled;$$('.move-buttons button').forEach(b=>b.disabled=!enabled)}

function update(dt){if(!state||paused)return;if((mode==='solo'||isHost)){if(state.phase==='aim'&&now()>state.turnEndsAt){fire(state,state.turn);log('⏱️ Автопостріл через завершення часу')}stepState(state,dt);if(mode==='online'&&now()-lastSnapshot>90)sendSnapshot();if(mode==='solo')updateAI()}else{stepState(state,dt)}handleEvents();syncHud();if(state.winner!==null&&!paused){setTimeout(()=>{if(!paused){paused=true;$('#pausePanel').classList.remove('hidden');$('#pausePanel h3').textContent=state.winner===localPlayer?'🏆 Перемога!':'💥 Поразка'}},900)}}
function updateAI(){if(!state||state.turn!==1||state.phase!=='aim'||state.winner!==null){aiPlan=null;return}if(!aiPlan){aiPlan=aiChoose(state,'normal');aiAt=now()+900;if(state.airdrop?.landed){const dir=Math.sign(state.airdrop.x-state.tanks[1].x);for(let i=0;i<16;i++)moveTank(state,1,dir,.08)}}else if(now()>aiAt){state.tanks[1].angle=aiPlan.angle;state.tanks[1].power=aiPlan.power;selectAmmo(state,1,aiPlan.selected);fire(state,1);aiPlan=null}}

function resize(){const dpr=Math.min(2,devicePixelRatio||1),r=canvas.getBoundingClientRect();canvas.width=Math.max(640,Math.floor(r.width*dpr));canvas.height=Math.max(360,Math.floor(r.height*dpr));ctx.setTransform(canvas.width/WORLD.w,0,0,canvas.height/WORLD.h,0,0)}
window.addEventListener('resize',resize);
function roundRect(x,y,w,h,r){ctx.beginPath();ctx.roundRect(x,y,w,h,r)}
function draw(){ctx.save();ctx.setTransform(canvas.width/WORLD.w,0,0,canvas.height/WORLD.h,0,0);const sky=ctx.createLinearGradient(0,0,0,WORLD.h);sky.addColorStop(0,'#4daeea');sky.addColorStop(.6,'#a7dded');sky.addColorStop(1,'#e8efb0');ctx.fillStyle=sky;ctx.fillRect(0,0,WORLD.w,WORLD.h);drawBackground();if(state){drawTrajectory();drawTerrain();drawFires();drawMines();drawDrop();drawTanks();drawProjectiles();drawWinner()}ctx.restore()}
function drawBackground(){ctx.fillStyle='#ffffffaa';for(let i=0;i<5;i++){const x=((now()*.012+i*370)%2000)-200,y=95+(i%3)*70;ctx.beginPath();ctx.ellipse(x,y,85,28,0,0,Math.PI*2);ctx.ellipse(x+65,y+5,65,23,0,0,Math.PI*2);ctx.fill()}ctx.fillStyle='#5f915b';ctx.beginPath();ctx.moveTo(0,610);for(let x=0;x<=WORLD.w;x+=80)ctx.lineTo(x,540+55*Math.sin(x/170)+25*Math.sin(x/61));ctx.lineTo(WORLD.w,WORLD.h);ctx.lineTo(0,WORLD.h);ctx.fill()}
function drawTerrain(){ctx.fillStyle='#38652f';ctx.beginPath();ctx.moveTo(0,WORLD.h);ctx.lineTo(0,state.terrain[0]);for(let i=1;i<state.terrain.length;i++)ctx.lineTo(i*WORLD.groundStep,state.terrain[i]);ctx.lineTo(WORLD.w,WORLD.h);ctx.closePath();ctx.fill();ctx.strokeStyle='#8fc54b';ctx.lineWidth=10;ctx.beginPath();for(let i=0;i<state.terrain.length;i++){const x=i*WORLD.groundStep,y=state.terrain[i];if(i===0)ctx.moveTo(x,y);else ctx.lineTo(x,y)}ctx.stroke()}
function drawTrajectory(){if(!state||state.phase!=='aim'||state.turn!==localPlayer)return;const t=state.tanks[localPlayer],pts=simulateTrajectory(state,t,t.selected,220,.045);ctx.fillStyle=settings.contrast?'#ff00f2':'#fff8b5';ctx.strokeStyle='#0005';for(let i=0;i<pts.length;i+=2){const p=pts[i],r=5-i*.012;if(r<=1)break;ctx.beginPath();ctx.arc(p.x,p.y,r,0,Math.PI*2);ctx.fill();ctx.stroke()}}
function drawTank(t){ctx.save();ctx.translate(t.x,t.y);ctx.rotate(t.rotation||0);if(!t.alive)ctx.globalAlpha=.45;ctx.fillStyle='#101b2a';roundRect(-32,5,64,22,10);ctx.fill();ctx.fillStyle=t.id===0?'#2085ea':'#e6473e';roundRect(-27,-9,54,23,8);ctx.fill();ctx.fillStyle=t.id===0?'#52c3ff':'#ff8e46';ctx.beginPath();ctx.arc(0,-12,15,Math.PI,0);ctx.fill();ctx.strokeStyle='#101b2a';ctx.lineWidth=9;const r=t.angle*Math.PI/180;ctx.beginPath();ctx.moveTo(Math.cos(r)*7,-Math.sin(r)*7);ctx.lineTo(Math.cos(r)*46,-Math.sin(r)*46);ctx.stroke();for(const x of[-20,0,20]){ctx.fillStyle='#070e17';ctx.beginPath();ctx.arc(x,18,9,0,Math.PI*2);ctx.fill()}if(t.shield>0){ctx.strokeStyle='#70e8ffbb';ctx.lineWidth=5;ctx.beginPath();ctx.arc(0,0,48,0,Math.PI*2);ctx.stroke()}ctx.restore()}
function drawTanks(){state.tanks.forEach(drawTank)}
function drawProjectiles(){for(const p of state.projectiles){ctx.fillStyle=p.air?'#ff6354':p.mini?'#ffe559':'#151515';ctx.beginPath();ctx.arc(p.x,p.y,p.air?8:p.mini?5:8,0,Math.PI*2);ctx.fill();ctx.strokeStyle='#fff8';ctx.stroke()}}
function drawMines(){for(const m of state.mines){ctx.fillStyle='#24272d';ctx.beginPath();ctx.arc(m.x,m.y,12,Math.PI,0);ctx.fill();ctx.fillStyle='#ff3131';ctx.fillRect(m.x-2,m.y-15,4,4)}}
function drawFires(){for(const f of state.fires){for(let i=0;i<9;i++){const x=f.x+(i-4)*15,y=terrainY(state,x)-8-Math.abs(Math.sin(now()/180+i))*18;ctx.fillStyle=i%2?'#ff3b19':'#ffd21e';ctx.beginPath();ctx.moveTo(x-7,terrainY(state,x));ctx.quadraticCurveTo(x,y-24,x+7,terrainY(state,x));ctx.fill()}}}
function drawDrop(){if(state.plane){ctx.save();ctx.translate(state.plane.x,state.plane.y);if(state.plane.vx<0)ctx.scale(-1,1);ctx.fillStyle='#394760';ctx.beginPath();ctx.moveTo(-58,0);ctx.lineTo(35,-10);ctx.lineTo(65,0);ctx.lineTo(35,10);ctx.closePath();ctx.fill();ctx.fillStyle='#d8e5ef';ctx.fillRect(-5,-24,30,48);ctx.restore()}if(state.airdrop){const d=state.airdrop;if(!d.landed){ctx.strokeStyle='#fff';ctx.lineWidth=3;ctx.beginPath();ctx.arc(d.x,d.y-30,34,Math.PI,0);ctx.stroke();ctx.beginPath();ctx.moveTo(d.x-34,d.y-30);ctx.lineTo(d.x-14,d.y);ctx.moveTo(d.x+34,d.y-30);ctx.lineTo(d.x+14,d.y);ctx.stroke()}ctx.fillStyle='#f3a72d';ctx.fillRect(d.x-17,d.y-15,34,30);ctx.strokeStyle='#704016';ctx.strokeRect(d.x-17,d.y-15,34,30);ctx.fillStyle='#fff';ctx.fillText('?',d.x-4,d.y+7)}}
function drawWinner(){if(state.winner===null)return;ctx.fillStyle='#07111ea8';ctx.fillRect(0,0,WORLD.w,WORLD.h);ctx.textAlign='center';ctx.font='900 88px system-ui';ctx.fillStyle=state.winner===localPlayer?'#ffd343':'#ff635d';ctx.fillText(state.winner===localPlayer?'ПЕРЕМОГА!':'ПОРАЗКА',WORLD.w/2,WORLD.h/2)}
function frame(t){const dt=Math.min(.05,(t-last)/1000);last=t;acc+=dt;while(acc>=1/60){update(1/60);acc-=1/60}draw();requestAnimationFrame(frame)}

function setMove(dir,on){if(on){moveDir=dir}else if(moveDir===dir)moveDir=0}
for(const[id,dir]of[['moveLeft',-1],['moveRight',1]]){const b=$(`#${id}`);b.addEventListener('pointerdown',e=>{e.preventDefault();b.setPointerCapture?.(e.pointerId);setMove(dir,true)});['pointerup','pointercancel','pointerleave'].forEach(ev=>b.addEventListener(ev,()=>setMove(dir,false)))}
setInterval(()=>{if(moveDir&&state&&state.turn===localPlayer&&state.phase==='aim'){sendOrApply({type:'move',dir:moveDir,dt:.08});if(mode==='online'&&!isHost){}syncHud()}},80);
$('#angle').addEventListener('input',e=>{if(!state)return;sendOrApply({type:'aim',angle:+e.target.value,power:+$('#power').value});$('#angleOut').textContent=`${e.target.value}°`});
$('#power').addEventListener('input',e=>{if(!state)return;sendOrApply({type:'aim',angle:+$('#angle').value,power:+e.target.value});$('#powerOut').textContent=`${e.target.value}%`});
$('#fireBtn').onclick=()=>sendOrApply({type:'fire'});
window.addEventListener('keydown',e=>{if(screens.game.classList.contains('active')){if(['ArrowLeft','a','A'].includes(e.key))setMove(-1,true);if(['ArrowRight','d','D'].includes(e.key))setMove(1,true);if(e.key===' '){e.preventDefault();sendOrApply({type:'fire'})}}});window.addEventListener('keyup',e=>{if(['ArrowLeft','a','A'].includes(e.key))setMove(-1,false);if(['ArrowRight','d','D'].includes(e.key))setMove(1,false)});

$('#soloBtn').onclick=startSolo;$('#createBtn').onclick=()=>connectRoom(randomCode(),true);$('#joinBtn').onclick=()=>{const code=$('#roomCode').value.toUpperCase().replace(/[^A-Z2-9]/g,'');if(code.length!==6)return toast('Введіть 6-символьний код');connectRoom(code,false)};$('#roomCode').addEventListener('input',e=>e.target.value=e.target.value.toUpperCase().replace(/[^A-Z2-9]/g,''));
$('#copyCodeBtn').onclick=async()=>{await navigator.clipboard?.writeText($('#lobbyCode').textContent);toast('Код скопійовано')};
$('#readyBtn').onclick=()=>{const key=isHost?'host':'guest';roomReady[key]=!roomReady[key];$('#readyBtn').textContent=roomReady[key]?'Не готовий':'Готовий';channels.ready?.send({host:isHost,ready:roomReady[key],nickname},connectedPeer);if(isHost&&roomReady.host&&roomReady.guest){const guest=$('#guestName').textContent.replace(' ✓','')||'Гість';state=createState(Date.now(),[nickname,guest]);state.turnEndsAt=now()+WORLD.turnSeconds*1000;channels.start.send(packState(state));startOnlineGame(packState(state))}};
$$('[data-back-menu]').forEach(b=>b.onclick=()=>{leaveOnline();show('menu')});
$('#howBtn').onclick=()=>$('#howDialog').showModal();$('#settingsBtn').onclick=()=>$('#settingsDialog').showModal();$$('.dialog-close').forEach(b=>b.onclick=()=>b.closest('dialog').close());
$('#soundToggle').checked=settings.sound;$('#vibrationToggle').checked=settings.vibration;$('#contrastToggle').checked=settings.contrast;$('#reducedMotionToggle').checked=settings.reduced;for(const[id,key]of[['soundToggle','sound'],['vibrationToggle','vibration'],['contrastToggle','contrast'],['reducedMotionToggle','reduced']])$(`#${id}`).onchange=e=>{settings[key]=e.target.checked;saveSettings()};saveSettings();
$('#leaveGameBtn').onclick=()=>{paused=true;$('#pausePanel').classList.remove('hidden')};$('#resumeBtn').onclick=()=>{paused=false;$('#pausePanel').classList.add('hidden')};$('#restartBtn').onclick=()=>{if(mode==='solo'){paused=false;$('#pausePanel').classList.add('hidden');startSolo()}else toast('Онлайн-рематч: поверніться в кімнату')};$('#exitBtn').onclick=()=>{paused=false;$('#pausePanel').classList.add('hidden');leaveOnline();state=null;show('menu')};
window.addEventListener('beforeunload',leaveOnline);if('serviceWorker'in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('./sw.js').catch(()=>{}));
resize();requestAnimationFrame(frame);
