import {
  TANKS,TANK_ORDER,WEAPONS,WORLD,createState,stepState,moveTank,fire,simulateTrajectory,terrainY,applyAction,aiChoose,normalizeTank
} from './core.js';

const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const screens={menu:$('#menu'),mode:$('#mode'),multiplayer:$('#multiplayer'),lobby:$('#lobby'),garage:$('#garage'),settings:$('#settings'),game:$('#game')};
const canvas=$('#gameCanvas'),ctx=canvas.getContext('2d',{alpha:false,desynchronized:true});

const LANGS={
  uk:{name:'Українська',battleBegins:'БИТВА ПОЧИНАЄТЬСЯ',playerName:'ІМ’Я ГРАВЦЯ',play:'ГРАТИ',multiplayer:'МУЛЬТИПЛЕЄР',garage:'ГАРАЖ',settings:'НАЛАШТУВАННЯ',chooseBattle:'ВИБЕРИ БІЙ',classicPromise:'Та сама перша Tank Arena, лише краще.',easyBot:'ЛЕГКИЙ БОТ',normalBot:'НОРМАЛЬНИЙ БОТ',hardBot:'СКЛАДНИЙ БОТ',crossplayText:'Android ↔ браузер ↔ ПК. Одна кімната на всіх пристроях.',createRoom:'СТВОРИТИ КІМНАТУ',join:'УВІЙТИ',serverChecking:'Перевірка сервера…',serverReady:'ОНЛАЙН-СЕРВЕР ГОТОВИЙ',serverFail:'СЕРВЕР НЕДОСТУПНИЙ',room:'КІМНАТА',playerOne:'ГРАВЕЦЬ 1',playerTwo:'ГРАВЕЦЬ 2',copyCode:'КОПІЮВАТИ КОД',ready:'Я ГОТОВИЙ',cancelReady:'СКАСУВАТИ ГОТОВНІСТЬ',reconnectNote:'Після короткого обриву гра перепідключиться автоматично.',garageText:'Кожен танк має один власний унікальний снаряд. Міняти його під час бою не можна.',language:'МОВА',sounds:'ЗВУКИ',vibration:'ВІБРАЦІЯ',highContrast:'КОНТРАСТНА ТРАЄКТОРІЯ',reducedMotion:'МЕНШЕ АНІМАЦІЙ',quality:'ЯКІСТЬ',rotate:'ПОВЕРНІТЬ ТЕЛЕФОН ГОРИЗОНТАЛЬНО',menu:'МЕНЮ',move:'РУХ',fuel:'ПАЛЬНЕ',angle:'КУТ',power:'СИЛА',fire:'ВОГОНЬ!',pause:'ПАУЗА',continue:'ПРОДОВЖИТИ',newBattle:'НОВИЙ БІЙ',exitMenu:'ВИЙТИ В МЕНЮ',howToPlay:'ЯК ГРАТИ',helpText:'Рухайте танк ліворуч або праворуч, налаштовуйте кут і силу, а потім стріляйте. Кожен танк має власний тип снаряда.',yourTurn:'ВАШ ХІД',enemyTurn:'ХІД СУПЕРНИКА',victory:'ПЕРЕМОГА!',defeat:'ПОРАЗКА',wind:'ВІТЕР',waiting:'ОЧІКУЄМО СУПЕРНИКА…',both:'ОБИДВА ГРАВЦІ В КІМНАТІ',connected:'З’ЄДНАНО',reconnecting:'ПЕРЕПІДКЛЮЧЕННЯ…',notReady:'НЕ ГОТОВИЙ',readyState:'ГОТОВИЙ',empty:'НЕМАЄ',selected:'ВИБРАНО',choose:'ОБРАТИ',weapon:'СНАРЯД',battleStarted:'БІЙ ПОЧАВСЯ!',onlineStarted:'ОНЛАЙН-БІЙ ПОЧАВСЯ!',codeCopied:'КОД СКОПІЙОВАНО',invalidCode:'Введіть 6 символів коду',actionRejected:'ДІЮ ВІДХИЛЕНО'},
  en:{name:'English',battleBegins:'THE BATTLE BEGINS',playerName:'PLAYER NAME',play:'PLAY',multiplayer:'MULTIPLAYER',garage:'GARAGE',settings:'SETTINGS',chooseBattle:'CHOOSE BATTLE',classicPromise:'The original Tank Arena feel, only better.',easyBot:'EASY BOT',normalBot:'NORMAL BOT',hardBot:'HARD BOT',crossplayText:'Android ↔ browser ↔ PC. One room on every device.',createRoom:'CREATE ROOM',join:'JOIN',serverChecking:'Checking server…',serverReady:'ONLINE SERVER READY',serverFail:'SERVER UNAVAILABLE',room:'ROOM',playerOne:'PLAYER 1',playerTwo:'PLAYER 2',copyCode:'COPY CODE',ready:'I AM READY',cancelReady:'CANCEL READY',reconnectNote:'The game reconnects automatically after a short interruption.',garageText:'Every tank has one unique shell. It cannot be changed during battle.',language:'LANGUAGE',sounds:'SOUNDS',vibration:'VIBRATION',highContrast:'HIGH-CONTRAST TRAJECTORY',reducedMotion:'REDUCED MOTION',quality:'QUALITY',rotate:'ROTATE YOUR PHONE TO LANDSCAPE',menu:'MENU',move:'MOVE',fuel:'FUEL',angle:'ANGLE',power:'POWER',fire:'FIRE!',pause:'PAUSE',continue:'CONTINUE',newBattle:'NEW BATTLE',exitMenu:'EXIT TO MENU',howToPlay:'HOW TO PLAY',helpText:'Move left or right, adjust angle and power, then fire. Each tank has its own shell type.',yourTurn:'YOUR TURN',enemyTurn:'OPPONENT TURN',victory:'VICTORY!',defeat:'DEFEAT',wind:'WIND',waiting:'WAITING FOR OPPONENT…',both:'BOTH PLAYERS ARE IN THE ROOM',connected:'CONNECTED',reconnecting:'RECONNECTING…',notReady:'NOT READY',readyState:'READY',empty:'EMPTY',selected:'SELECTED',choose:'SELECT',weapon:'SHELL',battleStarted:'BATTLE STARTED!',onlineStarted:'ONLINE BATTLE STARTED!',codeCopied:'CODE COPIED',invalidCode:'Enter a 6-character code',actionRejected:'ACTION REJECTED'},
  es:{name:'Español',battleBegins:'EMPIEZA LA BATALLA',playerName:'NOMBRE DEL JUGADOR',play:'JUGAR',multiplayer:'MULTIJUGADOR',garage:'GARAJE',settings:'AJUSTES',chooseBattle:'ELIGE BATALLA',classicPromise:'La primera Tank Arena, ahora mejor.',easyBot:'BOT FÁCIL',normalBot:'BOT NORMAL',hardBot:'BOT DIFÍCIL',crossplayText:'Android ↔ navegador ↔ PC. Una sala en todos los dispositivos.',createRoom:'CREAR SALA',join:'ENTRAR',serverChecking:'Comprobando servidor…',serverReady:'SERVIDOR EN LÍNEA LISTO',serverFail:'SERVIDOR NO DISPONIBLE',room:'SALA',playerOne:'JUGADOR 1',playerTwo:'JUGADOR 2',copyCode:'COPIAR CÓDIGO',ready:'ESTOY LISTO',cancelReady:'CANCELAR',reconnectNote:'El juego se reconecta automáticamente tras un corte breve.',garageText:'Cada tanque tiene un proyectil único. No se puede cambiar en combate.',language:'IDIOMA',sounds:'SONIDOS',vibration:'VIBRACIÓN',highContrast:'TRAYECTORIA DE ALTO CONTRASTE',reducedMotion:'MENOS ANIMACIONES',quality:'CALIDAD',rotate:'GIRA EL TELÉFONO EN HORIZONTAL',menu:'MENÚ',move:'MOVER',fuel:'COMBUSTIBLE',angle:'ÁNGULO',power:'FUERZA',fire:'¡FUEGO!',pause:'PAUSA',continue:'CONTINUAR',newBattle:'NUEVA BATALLA',exitMenu:'SALIR AL MENÚ',howToPlay:'CÓMO JUGAR',helpText:'Muévete a izquierda o derecha, ajusta ángulo y fuerza y dispara. Cada tanque tiene su propio proyectil.',yourTurn:'TU TURNO',enemyTurn:'TURNO RIVAL',victory:'¡VICTORIA!',defeat:'DERROTA',wind:'VIENTO',waiting:'ESPERANDO RIVAL…',both:'AMBOS JUGADORES EN LA SALA',connected:'CONECTADO',reconnecting:'RECONECTANDO…',notReady:'NO LISTO',readyState:'LISTO',empty:'VACÍO',selected:'ELEGIDO',choose:'ELEGIR',weapon:'PROYECTIL',battleStarted:'¡BATALLA INICIADA!',onlineStarted:'¡BATALLA EN LÍNEA!',codeCopied:'CÓDIGO COPIADO',invalidCode:'Introduce un código de 6 caracteres',actionRejected:'ACCIÓN RECHAZADA'},
  pl:{name:'Polski',battleBegins:'BITWA SIĘ ZACZYNA',playerName:'NAZWA GRACZA',play:'GRAJ',multiplayer:'MULTIPLAYER',garage:'GARAŻ',settings:'USTAWIENIA',chooseBattle:'WYBIERZ WALKĘ',classicPromise:'Pierwsza Tank Arena, tylko lepsza.',easyBot:'ŁATWY BOT',normalBot:'NORMALNY BOT',hardBot:'TRUDNY BOT',crossplayText:'Android ↔ przeglądarka ↔ PC. Jeden pokój na wszystkich urządzeniach.',createRoom:'UTWÓRZ POKÓJ',join:'DOŁĄCZ',serverChecking:'Sprawdzanie serwera…',serverReady:'SERWER ONLINE GOTOWY',serverFail:'SERWER NIEDOSTĘPNY',room:'POKÓJ',playerOne:'GRACZ 1',playerTwo:'GRACZ 2',copyCode:'KOPIUJ KOD',ready:'GOTOWY',cancelReady:'ANULUJ GOTOWOŚĆ',reconnectNote:'Gra automatycznie połączy się ponownie po krótkiej przerwie.',garageText:'Każdy czołg ma jeden wyjątkowy pocisk. Nie można go zmienić w walce.',language:'JĘZYK',sounds:'DŹWIĘKI',vibration:'WIBRACJE',highContrast:'KONTRASTOWA TRAJEKTORIA',reducedMotion:'MNIEJ ANIMACJI',quality:'JAKOŚĆ',rotate:'OBRÓĆ TELEFON POZIOMO',menu:'MENU',move:'RUCH',fuel:'PALIWO',angle:'KĄT',power:'SIŁA',fire:'OGNIA!',pause:'PAUZA',continue:'KONTYNUUJ',newBattle:'NOWA WALKA',exitMenu:'WYJDŹ DO MENU',howToPlay:'JAK GRAĆ',helpText:'Jedź w lewo lub prawo, ustaw kąt i siłę, a potem strzel. Każdy czołg ma własny pocisk.',yourTurn:'TWÓJ RUCH',enemyTurn:'RUCH RYWALA',victory:'ZWYCIĘSTWO!',defeat:'PORAŻKA',wind:'WIATR',waiting:'CZEKANIE NA RYWALA…',both:'OBAJ GRACZE W POKOJU',connected:'POŁĄCZONO',reconnecting:'PONOWNE ŁĄCZENIE…',notReady:'NIE GOTOWY',readyState:'GOTOWY',empty:'BRAK',selected:'WYBRANY',choose:'WYBIERZ',weapon:'POCISK',battleStarted:'WALKA ROZPOCZĘTA!',onlineStarted:'WALKA ONLINE!',codeCopied:'KOD SKOPIOWANY',invalidCode:'Wpisz 6 znaków kodu',actionRejected:'AKCJA ODRZUCONA'},
  de:{name:'Deutsch',battleBegins:'DIE SCHLACHT BEGINNT',playerName:'SPIELERNAME',play:'SPIELEN',multiplayer:'MEHRSPIELER',garage:'GARAGE',settings:'EINSTELLUNGEN',chooseBattle:'KAMPF WÄHLEN',classicPromise:'Das erste Tank Arena, nur besser.',easyBot:'LEICHTER BOT',normalBot:'NORMALER BOT',hardBot:'SCHWERER BOT',crossplayText:'Android ↔ Browser ↔ PC. Ein Raum auf allen Geräten.',createRoom:'RAUM ERSTELLEN',join:'BEITRETEN',serverChecking:'Server wird geprüft…',serverReady:'ONLINE-SERVER BEREIT',serverFail:'SERVER NICHT VERFÜGBAR',room:'RAUM',playerOne:'SPIELER 1',playerTwo:'SPIELER 2',copyCode:'CODE KOPIEREN',ready:'BEREIT',cancelReady:'BEREITSCHAFT ABBRECHEN',reconnectNote:'Nach einer kurzen Unterbrechung verbindet sich das Spiel automatisch neu.',garageText:'Jeder Panzer hat genau ein einzigartiges Geschoss. Im Kampf kann es nicht gewechselt werden.',language:'SPRACHE',sounds:'SOUNDS',vibration:'VIBRATION',highContrast:'KONTRASTREICHE FLUGBAHN',reducedMotion:'WENIGER ANIMATIONEN',quality:'QUALITÄT',rotate:'DREHE DAS HANDY INS QUERFORMAT',menu:'MENÜ',move:'FAHREN',fuel:'TREIBSTOFF',angle:'WINKEL',power:'KRAFT',fire:'FEUER!',pause:'PAUSE',continue:'WEITER',newBattle:'NEUER KAMPF',exitMenu:'ZUM MENÜ',howToPlay:'SO SPIELST DU',helpText:'Fahre links oder rechts, stelle Winkel und Kraft ein und feuere. Jeder Panzer hat sein eigenes Geschoss.',yourTurn:'DEIN ZUG',enemyTurn:'GEGNERZUG',victory:'SIEG!',defeat:'NIEDERLAGE',wind:'WIND',waiting:'WARTE AUF GEGNER…',both:'BEIDE SPIELER IM RAUM',connected:'VERBUNDEN',reconnecting:'NEU VERBINDEN…',notReady:'NICHT BEREIT',readyState:'BEREIT',empty:'LEER',selected:'AUSGEWÄHLT',choose:'WÄHLEN',weapon:'GESCHOSS',battleStarted:'KAMPF GESTARTET!',onlineStarted:'ONLINE-KAMPF GESTARTET!',codeCopied:'CODE KOPIERT',invalidCode:'Gib einen 6-stelligen Code ein',actionRejected:'AKTION ABGELEHNT'},
  fr:{name:'Français',battleBegins:'LA BATAILLE COMMENCE',playerName:'NOM DU JOUEUR',play:'JOUER',multiplayer:'MULTIJOUEUR',garage:'GARAGE',settings:'RÉGLAGES',chooseBattle:'CHOISIR LE COMBAT',classicPromise:'Le tout premier Tank Arena, en mieux.',easyBot:'BOT FACILE',normalBot:'BOT NORMAL',hardBot:'BOT DIFFICILE',crossplayText:'Android ↔ navigateur ↔ PC. Une seule salle sur tous les appareils.',createRoom:'CRÉER UNE SALLE',join:'REJOINDRE',serverChecking:'Vérification du serveur…',serverReady:'SERVEUR EN LIGNE PRÊT',serverFail:'SERVEUR INDISPONIBLE',room:'SALLE',playerOne:'JOUEUR 1',playerTwo:'JOUEUR 2',copyCode:'COPIER LE CODE',ready:'JE SUIS PRÊT',cancelReady:'ANNULER',reconnectNote:'Le jeu se reconnecte automatiquement après une courte coupure.',garageText:'Chaque char possède un seul obus unique. Il est impossible de le changer pendant le combat.',language:'LANGUE',sounds:'SONS',vibration:'VIBRATION',highContrast:'TRAJECTOIRE CONTRASTÉE',reducedMotion:'MOINS D’ANIMATIONS',quality:'QUALITÉ',rotate:'TOURNEZ LE TÉLÉPHONE EN MODE PAYSAGE',menu:'MENU',move:'DÉPLACER',fuel:'CARBURANT',angle:'ANGLE',power:'PUISSANCE',fire:'FEU !',pause:'PAUSE',continue:'CONTINUER',newBattle:'NOUVEAU COMBAT',exitMenu:'QUITTER VERS LE MENU',howToPlay:'COMMENT JOUER',helpText:'Déplacez-vous à gauche ou à droite, réglez l’angle et la puissance, puis tirez. Chaque char a son propre obus.',yourTurn:'VOTRE TOUR',enemyTurn:'TOUR ADVERSE',victory:'VICTOIRE !',defeat:'DÉFAITE',wind:'VENT',waiting:'EN ATTENTE DE L’ADVERSAIRE…',both:'LES DEUX JOUEURS SONT DANS LA SALLE',connected:'CONNECTÉ',reconnecting:'RECONNEXION…',notReady:'PAS PRÊT',readyState:'PRÊT',empty:'VIDE',selected:'SÉLECTIONNÉ',choose:'CHOISIR',weapon:'OBUS',battleStarted:'COMBAT LANCÉ !',onlineStarted:'COMBAT EN LIGNE !',codeCopied:'CODE COPIÉ',invalidCode:'Entrez un code à 6 caractères',actionRejected:'ACTION REFUSÉE'},
  ru:{name:'Русский',battleBegins:'БИТВА НАЧИНАЕТСЯ',playerName:'ИМЯ ИГРОКА',play:'ИГРАТЬ',multiplayer:'МУЛЬТИПЛЕЕР',garage:'ГАРАЖ',settings:'НАСТРОЙКИ',chooseBattle:'ВЫБЕРИ БОЙ',classicPromise:'Та самая первая Tank Arena, только лучше.',easyBot:'ЛЁГКИЙ БОТ',normalBot:'НОРМАЛЬНЫЙ БОТ',hardBot:'СЛОЖНЫЙ БОТ',crossplayText:'Android ↔ браузер ↔ ПК. Одна комната на всех устройствах.',createRoom:'СОЗДАТЬ КОМНАТУ',join:'ВОЙТИ',serverChecking:'Проверка сервера…',serverReady:'ОНЛАЙН-СЕРВЕР ГОТОВ',serverFail:'СЕРВЕР НЕДОСТУПЕН',room:'КОМНАТА',playerOne:'ИГРОК 1',playerTwo:'ИГРОК 2',copyCode:'КОПИРОВАТЬ КОД',ready:'Я ГОТОВ',cancelReady:'ОТМЕНИТЬ ГОТОВНОСТЬ',reconnectNote:'После короткого обрыва игра переподключится автоматически.',garageText:'У каждого танка один уникальный снаряд. Менять его во время боя нельзя.',language:'ЯЗЫК',sounds:'ЗВУКИ',vibration:'ВИБРАЦИЯ',highContrast:'КОНТРАСТНАЯ ТРАЕКТОРИЯ',reducedMotion:'МЕНЬШЕ АНИМАЦИЙ',quality:'КАЧЕСТВО',rotate:'ПОВЕРНИТЕ ТЕЛЕФОН ГОРИЗОНТАЛЬНО',menu:'МЕНЮ',move:'ДВИЖЕНИЕ',fuel:'ТОПЛИВО',angle:'УГОЛ',power:'СИЛА',fire:'ОГОНЬ!',pause:'ПАУЗА',continue:'ПРОДОЛЖИТЬ',newBattle:'НОВЫЙ БОЙ',exitMenu:'ВЫЙТИ В МЕНЮ',howToPlay:'КАК ИГРАТЬ',helpText:'Двигайте танк влево или вправо, настраивайте угол и силу, затем стреляйте. У каждого танка свой снаряд.',yourTurn:'ВАШ ХОД',enemyTurn:'ХОД СОПЕРНИКА',victory:'ПОБЕДА!',defeat:'ПОРАЖЕНИЕ',wind:'ВЕТЕР',waiting:'ЖДЁМ СОПЕРНИКА…',both:'ОБА ИГРОКА В КОМНАТЕ',connected:'ПОДКЛЮЧЕНО',reconnecting:'ПЕРЕПОДКЛЮЧЕНИЕ…',notReady:'НЕ ГОТОВ',readyState:'ГОТОВ',empty:'НЕТ',selected:'ВЫБРАНО',choose:'ВЫБРАТЬ',weapon:'СНАРЯД',battleStarted:'БОЙ НАЧАЛСЯ!',onlineStarted:'ОНЛАЙН-БОЙ НАЧАЛСЯ!',codeCopied:'КОД СКОПИРОВАН',invalidCode:'Введите 6 символов кода',actionRejected:'ДЕЙСТВИЕ ОТКЛОНЕНО'}
};

const settings=Object.assign({sound:true,vibration:true,contrast:false,reduced:false,quality:'high',tank:'classic',lang:'uk'},JSON.parse(localStorage.getItem('ta4-settings')||'{}'));
if(!LANGS[settings.lang])settings.lang='uk';
let nickname=localStorage.getItem('ta4-name')||'CREDESASQ';
let state=null,mode='solo',difficulty='normal',localPlayer=0,ws=null,roomCode='',clientId=localStorage.getItem('ta4-client')||crypto.randomUUID(),ready=false,roomInfo=null;
let last=performance.now(),acc=0,moveDir=0,cameraScale=1,cameraX=0,cameraY=0,aiPlan=null,aiAt=0,eventCursor=0,toastTimer=0,paused=false,audioCtx=null,pingAt=0,ping=0,reconnectTimer=null,lastRevision=-1,serverOffset=0;
localStorage.setItem('ta4-client',clientId);$('#nickname').value=nickname;
const tr=key=>LANGS[settings.lang]?.[key]||LANGS.en[key]||key;

function populateLanguages(){for(const sel of [$('#languageSelect'),$('#settingsLanguageSelect')]){sel.innerHTML='';for(const [id,lang] of Object.entries(LANGS)){const o=document.createElement('option');o.value=id;o.textContent=lang.name;sel.append(o)}sel.value=settings.lang;sel.onchange=e=>{settings.lang=e.target.value;saveSettings();applyLanguage();renderGarage();syncHud();}}}
function applyLanguage(){document.documentElement.lang=settings.lang;$$('[data-i18n]').forEach(el=>{const key=el.dataset.i18n;if(LANGS[settings.lang]?.[key])el.textContent=LANGS[settings.lang][key]});$('#roomCode').placeholder=settings.lang==='uk'?'КОД КІМНАТИ':'ROOM CODE';if(roomInfo)renderRoom();if(state)syncHud();}
function show(name){Object.values(screens).forEach(s=>s.classList.remove('active'));screens[name]?.classList.add('active')}
function saveSettings(){localStorage.setItem('ta4-settings',JSON.stringify(settings));document.body.classList.toggle('reduced',settings.reduced)}
function toast(text){const el=$('#toast');el.textContent=text;el.classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>el.classList.remove('show'),1900)}
function log(text){const el=document.createElement('div');el.className='log-line';el.textContent=text;$('#combatLog').prepend(el);setTimeout(()=>el.remove(),4800)}
function beep(freq=180,dur=.12,type='sine',vol=.07){if(!settings.sound)return;try{audioCtx??=new AudioContext();if(audioCtx.state==='suspended')audioCtx.resume();const o=audioCtx.createOscillator(),g=audioCtx.createGain();o.type=type;o.frequency.value=freq;g.gain.setValueAtTime(vol,audioCtx.currentTime);g.gain.exponentialRampToValueAtTime(.001,audioCtx.currentTime+dur);o.connect(g).connect(audioCtx.destination);o.start();o.stop(audioCtx.currentTime+dur)}catch{}}
function vibrate(pattern=35){if(settings.vibration&&navigator.vibrate)navigator.vibrate(pattern)}
function now(){return Date.now()+serverOffset}
function randomCode(){const chars='ABCDEFGHJKLMNPQRSTUVWXYZ23456789',v=new Uint8Array(6);crypto.getRandomValues(v);return[...v].map(x=>chars[x%chars.length]).join('')}
function cleanName(){nickname=$('#nickname').value.trim().slice(0,16)||'Player';$('#nickname').value=nickname;localStorage.setItem('ta4-name',nickname);return nickname}
function wsEndpoint(){const scheme=location.protocol==='https:'?'wss:':'ws:';return`${scheme}//${location.host}/api/ws`}

function resizeCanvas(){
  const dpr=Math.min(2,Math.max(1,window.devicePixelRatio||1));
  const w=Math.max(1,Math.round(window.innerWidth*dpr));
  const h=Math.max(1,Math.round((window.visualViewport?.height||window.innerHeight)*dpr));
  if(canvas.width!==w||canvas.height!==h){canvas.width=w;canvas.height=h;}
  cameraScale=Math.max(w/WORLD.w,h/WORLD.h);
  cameraX=(w-WORLD.w*cameraScale)/2;
  cameraY=(h-WORLD.h*cameraScale)/2;
}
async function enterGameMode(){
  resizeCanvas();
  try{if(!document.fullscreenElement&&document.documentElement.requestFullscreen)await document.documentElement.requestFullscreen({navigationUI:'hide'});}catch{}
  try{await screen.orientation?.lock?.('landscape');}catch{}
}
function leaveGameMode(){try{screen.orientation?.unlock?.()}catch{}}

function startSolo(level='normal'){
  closeSocket();cleanName();mode='solo';difficulty=level;localPlayer=0;
  const botType=TANK_ORDER[Math.floor(Math.random()*TANK_ORDER.length)];
  state=createState(Date.now(),[nickname,'BOT RANGER'],[settings.tank,botType]);state.turnEndsAt=Date.now()+WORLD.turnSeconds*1000;eventCursor=0;aiPlan=null;paused=false;syncHud();show('game');enterGameMode();toast(tr('battleStarted'));beep(360,.14,'square');
}
function openMultiplayer(){cleanName();show('multiplayer');probeServer()}
function probeServer(){const dot=$('#serverDot'),text=$('#serverText');dot.style.background='#ffbf49';text.textContent=tr('serverChecking');fetch('/api/health',{cache:'no-store'}).then(r=>r.ok?r.json():Promise.reject()).then(()=>{dot.style.background='#56e48a';text.textContent=tr('serverReady')}).catch(()=>{dot.style.background='#ff5e67';text.textContent=tr('serverFail')})}
function connectOnline(create,code){
  cleanName();closeSocket(false);mode='online';localPlayer=create?0:1;ready=false;roomCode=(code||randomCode()).toUpperCase();$('#lobbyCode').textContent=roomCode;$('#lobbyStatus').textContent=tr('reconnecting');$('#readyBtn').disabled=true;$('#readyBtn').querySelector('b').textContent=tr('ready');show('lobby');
  const url=new URL(wsEndpoint());url.searchParams.set('mode',create?'create':'join');url.searchParams.set('room',roomCode);url.searchParams.set('name',nickname);url.searchParams.set('client',clientId);url.searchParams.set('tank',settings.tank);
  try{ws=new WebSocket(url);ws.onopen=()=>{$('#lobbyStatus').textContent=tr('connected');$('#readyBtn').disabled=false;pingAt=Date.now();ws.send(JSON.stringify({type:'ping',t:pingAt}))};ws.onmessage=e=>handleNetwork(JSON.parse(e.data));ws.onclose=e=>{if(mode==='online'){setNetwork(false);if(e.code!==1000){$('#lobbyStatus').textContent=tr('reconnecting');scheduleReconnect(create)}}};ws.onerror=()=>{$('#lobbyStatus').textContent=tr('serverFail')}}catch{scheduleReconnect(create)}
}
function scheduleReconnect(create){clearTimeout(reconnectTimer);reconnectTimer=setTimeout(()=>{if(mode==='online'){const inBattle=screens.game.classList.contains('active');connectOnline(create,roomCode);if(inBattle)show('game');}},1200)}
function closeSocket(reset=true){clearTimeout(reconnectTimer);reconnectTimer=null;if(ws){try{ws.onclose=null;ws.close(1000,'leave')}catch{}ws=null}if(reset){roomCode='';roomInfo=null;ready=false}}
function sendNet(data){if(ws?.readyState===WebSocket.OPEN)ws.send(JSON.stringify(data))}
function handleNetwork(msg){
  if(msg.serverNow)serverOffset=msg.serverNow-Date.now();
  if(msg.type==='error'){toast(msg.message||tr('serverFail'));$('#lobbyStatus').textContent=msg.message||tr('serverFail');return}
  if(msg.type==='welcome'){roomCode=msg.code;localPlayer=msg.player;$('#lobbyCode').textContent=roomCode;roomInfo=msg.room;renderRoom();if(msg.state){state=msg.state;startOnlineGame()}return}
  if(msg.type==='room'){roomInfo=msg;renderRoom();return}
  if(msg.type==='started'){state=msg.state;lastRevision=-1;startOnlineGame();return}
  if(msg.type==='snapshot'){if(msg.revision<=lastRevision)return;lastRevision=msg.revision;state=msg.state;handleEvents();syncHud();return}
  if(msg.type==='rejected'){toast(msg.reason||tr('actionRejected'));return}
  if(msg.type==='pong'){ping=Math.max(0,Date.now()-msg.t);return}
}
function renderRoom(){if(!roomInfo)return;const names=roomInfo.names||[],r=roomInfo.ready||[],c=roomInfo.connected||[];$('#hostName').textContent=names[0]||'…';$('#guestName').textContent=names[1]||'…';$('#hostState').textContent=r[0]?tr('readyState'):c[0]?tr('notReady'):tr('empty');$('#guestState').textContent=r[1]?tr('readyState'):c[1]?tr('notReady'):tr('empty');$('#readyBtn').disabled=!!roomInfo.started;$('#readyBtn').style.display=roomInfo.started?'none':'';$('#lobbyStatus').textContent=roomInfo.started?tr('battleStarted'):(c[0]&&c[1]?tr('both'):tr('waiting'))}
function setNetwork(ok){if(!state)return;$('#networkLabel')?.remove?.();const label=mode==='solo'?'SOLO':ok?`ONLINE ${ping?ping+'ms':''}`:'RECONNECT';$('#p2TankName').dataset.net=label}
function startOnlineGame(){mode='online';paused=false;eventCursor=state?.events?.length||0;syncHud();show('game');enterGameMode();toast(tr('onlineStarted'))}

function tankDescription(id){const spec=TANKS[id],w=WEAPONS[spec.weapon];const names={classic:{uk:'Збалансований постріл',en:'Balanced shell',es:'Proyectil equilibrado',pl:'Zrównoważony pocisk',de:'Ausgewogenes Geschoss',fr:'Obus équilibré',ru:'Сбалансированный снаряд'},tiger:{uk:'Важкий вибух',en:'Heavy blast',es:'Explosión pesada',pl:'Ciężki wybuch',de:'Schwere Explosion',fr:'Explosion lourde',ru:'Тяжёлый взрыв'},storm:{uk:'П’ять міні-бомб',en:'Five mini-bombs',es:'Cinco minibombas',pl:'Pięć minibomb',de:'Fünf Minibomben',fr:'Cinq mini-bombes',ru:'Пять мини-бомб'},pyro:{uk:'Палаюча зона',en:'Burning zone',es:'Zona incendiaria',pl:'Płonąca strefa',de:'Brandzone',fr:'Zone en feu',ru:'Горящая зона'},mole:{uk:'Пробиває ґрунт',en:'Drills into ground',es:'Perfora el terreno',pl:'Wierci w ziemi',de:'Bohrt in den Boden',fr:'Perce le sol',ru:'Пробивает землю'},comet:{uk:'Один рикошет',en:'One ricochet',es:'Un rebote',pl:'Jeden rykoszet',de:'Ein Abpraller',fr:'Un ricochet',ru:'Один рикошет'}};return names[id]?.[settings.lang]||names[id]?.en||w.name}
function renderGarage(){const box=$('#tankCards');box.innerHTML='';for(const id of TANK_ORDER){const spec=TANKS[id],w=WEAPONS[spec.weapon],b=document.createElement('button');b.className=`tank-card-choice ${settings.tank===id?'selected':''}`;b.style.setProperty('--tank',spec.color);b.style.setProperty('--accent',spec.accent);b.innerHTML=`<div class="tank-preview"><i class="tracks"></i><i class="body"></i><i class="turret"></i><i class="barrel"></i></div><b>${spec.name}</b><small>${tankDescription(id)}</small><span class="weapon-badge">${tr('weapon')}: ${w.name}</span><span>${settings.tank===id?tr('selected'):tr('choose')}</span>`;b.onclick=()=>{settings.tank=id;saveSettings();renderGarage();beep(420,.08)};box.append(b)}}
function sendAction(action){if(!state||paused)return;if(mode==='online'){sendNet({type:'action',action});if(action.type==='aim'){state.tanks[localPlayer].angle=action.angle;state.tanks[localPlayer].power=action.power}return}applyAction(state,localPlayer,action)}
function handleEvents(){if(!state?.events)return;while(eventCursor<state.events.length){const e=state.events[eventCursor++];if(e.type==='fire'){beep(125,.18,'sawtooth',.12);vibrate(45);const tank=state.tanks[e.player];log(`${tank.name}: ${WEAPONS[e.weapon]?.name||''}`)}else if(e.type==='explode'){beep(58,.33,'square',.14);vibrate([45,25,80]);log('💥') }else if(e.type==='turn')toast(e.player===localPlayer?tr('yourTurn'):tr('enemyTurn'));else if(e.type==='burn')log(`🔥 -${e.amount} HP`)}}
function syncHud(){if(!state)return;screens.game.classList.toggle('winner',state.winner!==null);const[a,b]=state.tanks;$('#p1Name').textContent=a.name;$('#p2Name').textContent=b.name;$('#p1HpText').textContent=`${Math.ceil(a.hp)} HP`;$('#p2HpText').textContent=`${Math.ceil(b.hp)} HP`;$('#p1Hp').style.width=`${Math.max(0,a.hp/a.maxHp*100)}%`;$('#p2Hp').style.width=`${Math.max(0,b.hp/b.maxHp*100)}%`;$('#p1TankName').textContent=TANKS[normalizeTank(a.tankType)].name;$('#p2TankName').textContent=TANKS[normalizeTank(b.tankType)].name+(mode==='online'&&ping?` • ${ping}ms`:'');const own=state.tanks[localPlayer];$('#fuelBar').style.width=`${own.fuel/WORLD.turnFuel*100}%`;$('#fuelText').textContent=Math.ceil(own.fuel);$('#angleOut').textContent=`${Math.round(own.angle)}°`;$('#powerOut').textContent=Math.round(own.power);$('#windLabel').textContent=`${tr('wind')} ${state.wind>0?'→':state.wind<0?'←':'•'} ${Math.abs(state.wind)}`;const mine=state.turn===localPlayer;$('#turnLabel').textContent=state.winner!==null?(state.winner===localPlayer?tr('victory'):tr('defeat')):(mine?tr('yourTurn'):tr('enemyTurn'));$('#timerLabel').textContent=state.phase==='aim'?Math.max(0,Math.ceil((state.turnEndsAt-now())/1000)):'•';const enabled=mine&&state.phase==='aim'&&state.winner===null&&!paused;for(const id of ['fireBtn','moveLeft','moveRight','angleMinus','anglePlus','powerMinus','powerPlus'])$('#'+id).disabled=!enabled}
function update(dt){if(!state||paused)return;if(mode==='solo'){if(state.phase==='aim'&&Date.now()>=state.turnEndsAt)fire(state,state.turn);stepState(state,dt);updateAI()}handleEvents();syncHud();if(mode==='online'&&Date.now()-pingAt>4000){pingAt=Date.now();sendNet({type:'ping',t:pingAt})}if(state.winner!==null&&!$('#pausePanel').classList.contains('shown'))setTimeout(()=>{if(state?.winner!==null){paused=true;$('#pausePanel').classList.remove('hidden');$('#pausePanel').classList.add('shown');$('#pausePanel h2').textContent=state.winner===localPlayer?tr('victory'):tr('defeat')}},800)}
function updateAI(){if(state.turn!==1||state.phase!=='aim'||state.winner!==null){aiPlan=null;return}if(!aiPlan){aiPlan=aiChoose(state,difficulty);aiAt=Date.now()+(difficulty==='hard'?600:difficulty==='easy'?1300:900);if(Math.abs(state.tanks[1].x-state.tanks[0].x)>850&&state.tanks[1].fuel>10){const dir=Math.sign(state.tanks[0].x-state.tanks[1].x);for(let i=0;i<8;i++)moveTank(state,1,dir,.09)}}else if(Date.now()>=aiAt){state.tanks[1].angle=aiPlan.angle;state.tanks[1].power=aiPlan.power;fire(state,1);aiPlan=null}}

function draw(){resizeCanvas();ctx.setTransform(1,0,0,1,0,0);ctx.fillStyle='#4c8fd8';ctx.fillRect(0,0,canvas.width,canvas.height);ctx.setTransform(cameraScale,0,0,cameraScale,cameraX,cameraY);drawSky();if(state){drawTrajectory();drawTerrain();drawFireZones();state.tanks.forEach(drawTank);drawProjectiles();drawWinner()}}
function drawSky(){const g=ctx.createLinearGradient(0,0,0,WORLD.h);g.addColorStop(0,'#4c8fd8');g.addColorStop(.62,'#75afe4');g.addColorStop(1,'#beddf4');ctx.fillStyle=g;ctx.fillRect(0,0,WORLD.w,WORLD.h);drawCloud(75,130,1.15);drawCloud(420,180,.9);drawCloud(865,210,1);drawCloud(1320,245,.92);drawMountains('#7196ad',515,165,38);drawMountains('#52778f',555,150,50)}
function drawCloud(x,y,s){ctx.save();ctx.translate(x,y);ctx.scale(s,s);ctx.fillStyle='#ffffffa8';for(const [cx,cy,r] of [[0,10,35],[38,0,45],[80,12,34],[40,25,50]]){ctx.beginPath();ctx.arc(cx,cy,r,0,Math.PI*2);ctx.fill()}ctx.restore()}
function drawMountains(color,base,step,offset){ctx.fillStyle=color;ctx.beginPath();ctx.moveTo(0,WORLD.h);ctx.lineTo(0,base);let peak=true;for(let x=0;x<=WORLD.w+step;x+=step/2){ctx.lineTo(x,peak?base-offset-105:base+10);peak=!peak}ctx.lineTo(WORLD.w,WORLD.h);ctx.closePath();ctx.fill()}
function drawTerrain(){ctx.fillStyle='#3c6d39';ctx.beginPath();ctx.moveTo(0,WORLD.h);ctx.lineTo(0,state.terrain[0]);for(let i=1;i<state.terrain.length;i++)ctx.lineTo(i*WORLD.groundStep,state.terrain[i]);ctx.lineTo(WORLD.w,WORLD.h);ctx.closePath();ctx.fill();ctx.strokeStyle='#83b953';ctx.lineWidth=8;ctx.beginPath();state.terrain.forEach((y,i)=>i?ctx.lineTo(i*WORLD.groundStep,y):ctx.moveTo(0,y));ctx.stroke()}
function drawTrajectory(){if(state.phase!=='aim'||state.turn!==localPlayer||state.winner!==null)return;const pts=simulateTrajectory(state,state.tanks[localPlayer],230,.045);ctx.fillStyle=settings.contrast?'#ff00e5':'#ffffff';for(let i=0;i<pts.length;i+=2){const p=pts[i];ctx.globalAlpha=Math.max(.25,1-i/pts.length);ctx.beginPath();ctx.arc(p.x,p.y,5,0,Math.PI*2);ctx.fill()}ctx.globalAlpha=1}
function drawTank(t){const spec=TANKS[normalizeTank(t.tankType)];ctx.save();ctx.translate(t.x,t.y);ctx.rotate(t.rotation||0);if(!t.alive)ctx.rotate(.25);ctx.fillStyle='#282d3e';roundRect(-49,5,98,29,14);ctx.fill();for(const x of[-35,-17,1,19,37]){ctx.fillStyle='#4e5464';ctx.beginPath();ctx.arc(x,20,8,0,Math.PI*2);ctx.fill()}ctx.fillStyle=spec.color;roundRect(-42,-20,84,30,8);ctx.fill();ctx.fillStyle=spec.accent;roundRect(-18,-42,48,26,12);ctx.fill();const r=t.angle*Math.PI/180;ctx.strokeStyle='#365f8b';ctx.lineWidth=10;ctx.lineCap='round';ctx.beginPath();ctx.moveTo(Math.cos(r)*9,-Math.sin(r)*9-25);ctx.lineTo(Math.cos(r)*62,-Math.sin(r)*62-25);ctx.stroke();ctx.restore()}
function roundRect(x,y,w,h,r){ctx.beginPath();ctx.roundRect(x,y,w,h,r)}
function drawProjectiles(){for(const p of state.projectiles||[]){const weapon=WEAPONS[p.weapon]||WEAPONS.classic;ctx.fillStyle=p.mini?'#ffe45c':weapon.behavior==='napalm'?'#ff6b32':weapon.behavior==='drill'?'#9de1a8':'#212636';ctx.beginPath();ctx.arc(p.x,p.y,p.mini?5:8,0,Math.PI*2);ctx.fill()}}
function drawFireZones(){for(const f of state.fires||[]){for(let i=0;i<9;i++){const x=f.x+(i-4)*16,y=terrainY(state,x)-8-Math.abs(Math.sin(performance.now()/170+i))*22;ctx.fillStyle=i%2?'#ff4d20':'#ffd327';ctx.beginPath();ctx.moveTo(x-8,terrainY(state,x));ctx.quadraticCurveTo(x,y-25,x+8,terrainY(state,x));ctx.fill()}}}
function drawWinner(){if(state.winner===null)return;ctx.fillStyle='#132c49a8';ctx.fillRect(0,0,WORLD.w,WORLD.h);ctx.textAlign='center';ctx.font='900 96px Arial Black';ctx.fillStyle=state.winner===localPlayer?'#ffe36d':'#ff6465';ctx.strokeStyle='#17365b';ctx.lineWidth=11;const text=state.winner===localPlayer?tr('victory'):tr('defeat');ctx.strokeText(text,WORLD.w/2,WORLD.h/2);ctx.fillText(text,WORLD.w/2,WORLD.h/2)}
function frame(t){const dt=Math.min(.05,(t-last)/1000);last=t;acc+=dt;while(acc>=1/60){update(1/60);acc-=1/60}draw();requestAnimationFrame(frame)}

function setMove(dir,on){if(on)moveDir=dir;else if(moveDir===dir)moveDir=0}
setInterval(()=>{if(!moveDir||!state||paused)return;if(state.turn!==localPlayer||state.phase!=='aim'||state.winner!==null)return;sendAction({type:'move',dir:moveDir,dt:.09})},90);
function changeAim(deltaAngle=0,deltaPower=0){if(!state)return;const t=state.tanks[localPlayer],angle=Math.max(5,Math.min(175,t.angle+deltaAngle)),power=Math.max(20,Math.min(100,t.power+deltaPower));sendAction({type:'aim',angle,power})}
function bindHold(id,down,up){const b=$('#'+id);for(const ev of ['pointerdown','touchstart'])b.addEventListener(ev,e=>{e.preventDefault();b.setPointerCapture?.(e.pointerId);down()},{passive:false});for(const ev of ['pointerup','pointercancel','pointerleave','touchend'])b.addEventListener(ev,e=>{e.preventDefault();up()},{passive:false})}
function bindRepeat(id,fn){let timer=0;const stop=()=>{clearTimeout(timer);clearInterval(timer);timer=0};const start=e=>{e.preventDefault();fn();clearTimeout(timer);timer=setTimeout(()=>{timer=setInterval(fn,75)},280)};const b=$('#'+id);b.addEventListener('pointerdown',start);for(const ev of ['pointerup','pointercancel','pointerleave'])b.addEventListener(ev,stop);window.addEventListener('pointerup',stop)}

$('#playBtn').onclick=()=>show('mode');$('#multiBtn').onclick=openMultiplayer;$('#garageBtn').onclick=()=>{renderGarage();show('garage')};$('#settingsBtn').onclick=()=>show('settings');$('#helpBtn').onclick=()=>$('#helpDialog').showModal();$$('[data-back]').forEach(b=>b.onclick=()=>show(b.dataset.back));
$('#easyBtn').onclick=()=>startSolo('easy');$('#normalBtn').onclick=()=>startSolo('normal');$('#hardBtn').onclick=()=>startSolo('hard');$('#createBtn').onclick=()=>connectOnline(true,randomCode());$('#joinBtn').onclick=()=>{const c=$('#roomCode').value.toUpperCase().replace(/[^A-Z0-9]/g,'');if(c.length!==6)return toast(tr('invalidCode'));connectOnline(false,c)};$('#roomCode').oninput=e=>e.target.value=e.target.value.toUpperCase().replace(/[^A-Z0-9]/g,'');$('#copyCodeBtn').onclick=async()=>{await navigator.clipboard?.writeText(roomCode);toast(tr('codeCopied'))};$('#readyBtn').onclick=()=>{ready=!ready;sendNet({type:'ready',ready});$('#readyBtn').querySelector('b').textContent=ready?tr('cancelReady'):tr('ready')};$('#leaveLobbyBtn').onclick=()=>{closeSocket();mode='solo';show('multiplayer')};
$('#fireBtn').onclick=()=>sendAction({type:'fire'});bindRepeat('angleMinus',()=>changeAim(-2,0));bindRepeat('anglePlus',()=>changeAim(2,0));bindRepeat('powerMinus',()=>changeAim(0,-2));bindRepeat('powerPlus',()=>changeAim(0,2));bindHold('moveLeft',()=>setMove(-1,true),()=>setMove(-1,false));bindHold('moveRight',()=>setMove(1,true),()=>setMove(1,false));
$('#pauseBtn').onclick=()=>{paused=true;$('#pausePanel').classList.remove('hidden')};$('#resumeBtn').onclick=()=>{paused=false;$('#pausePanel').classList.add('hidden');$('#pausePanel').classList.remove('shown')};$('#restartBtn').onclick=()=>{if(mode==='solo')startSolo(difficulty);else sendNet({type:'rematch'});$('#pausePanel').classList.add('hidden');$('#pausePanel').classList.remove('shown')};$('#exitBtn').onclick=()=>{closeSocket();mode='solo';state=null;paused=false;screens.game.classList.remove('winner');$('#pausePanel').classList.add('hidden');$('#pausePanel').classList.remove('shown');leaveGameMode();show('menu')};
for(const d of $$('dialog'))d.querySelector('.dialog-x')?.addEventListener('click',()=>d.close());
$('#soundToggle').checked=settings.sound;$('#vibrationToggle').checked=settings.vibration;$('#contrastToggle').checked=settings.contrast;$('#motionToggle').checked=settings.reduced;$('#qualitySelect').value=settings.quality;$('#soundToggle').onchange=e=>{settings.sound=e.target.checked;saveSettings()};$('#vibrationToggle').onchange=e=>{settings.vibration=e.target.checked;saveSettings()};$('#contrastToggle').onchange=e=>{settings.contrast=e.target.checked;saveSettings()};$('#motionToggle').onchange=e=>{settings.reduced=e.target.checked;saveSettings()};$('#qualitySelect').onchange=e=>{settings.quality=e.target.value;saveSettings()};
window.addEventListener('keydown',e=>{if(!screens.game.classList.contains('active'))return;if(['ArrowLeft','a','A'].includes(e.key))setMove(-1,true);if(['ArrowRight','d','D'].includes(e.key))setMove(1,true);if(['ArrowUp','w','W'].includes(e.key))changeAim(2,0);if(['ArrowDown','s','S'].includes(e.key))changeAim(-2,0);if(['q','Q'].includes(e.key))changeAim(0,-2);if(['e','E'].includes(e.key))changeAim(0,2);if(e.code==='Space'){e.preventDefault();sendAction({type:'fire'})}});window.addEventListener('keyup',e=>{if(['ArrowLeft','a','A'].includes(e.key))setMove(-1,false);if(['ArrowRight','d','D'].includes(e.key))setMove(1,false)});window.addEventListener('beforeunload',()=>closeSocket());window.addEventListener('resize',resizeCanvas);window.visualViewport?.addEventListener('resize',resizeCanvas);document.addEventListener('visibilitychange',()=>{if(!document.hidden)resizeCanvas()});
if('serviceWorker'in navigator)navigator.serviceWorker.register('/sw.js').then(r=>r.update()).catch(()=>{});
populateLanguages();saveSettings();applyLanguage();renderGarage();resizeCanvas();requestAnimationFrame(frame);
