import {AMMO,AMMO_ORDER,WORLD,createState,stepState,moveTank,selectAmmo,fire,simulateTrajectory,terrainY,applyAction,aiChoose,advanceTurn} from './core.js';

const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const screens={menu:$('#menu'),mode:$('#mode'),multiplayer:$('#multiplayer'),lobby:$('#lobby'),garage:$('#garage'),settings:$('#settings'),game:$('#game')};
const canvas=$('#gameCanvas'),ctx=canvas.getContext('2d',{alpha:false,desynchronized:true});
const settings=Object.assign({sound:true,vibration:true,contrast:false,reduced:false,quality:'high',tank:0},JSON.parse(localStorage.getItem('ta-classic-settings')||'{}'));
let nickname=localStorage.getItem('ta-classic-name')||'CREDESASQ';
let state=null,mode='solo',difficulty='normal',localPlayer=0,ws=null,roomCode='',clientId=localStorage.getItem('ta-client-id')||crypto.randomUUID(),ready=false,roomInfo=null;
let last=performance.now(),acc=0,moveDir=0,aiPlan=null,aiAt=0,eventCursor=0,toastTimer=0,paused=false,audioCtx=null,pingAt=0,ping=0,reconnectTimer=null,lastRevision=-1,lastServerNow=Date.now(),serverOffset=0;
localStorage.setItem('ta-client-id',clientId);$('#nickname').value=nickname;

function show(name){Object.values(screens).forEach(s=>s.classList.remove('active'));screens[name]?.classList.add('active')}
function saveSettings(){localStorage.setItem('ta-classic-settings',JSON.stringify(settings));document.body.classList.toggle('reduced',settings.reduced)}
function toast(text){const el=$('#toast');el.textContent=text;el.classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>el.classList.remove('show'),1900)}
function log(text){const el=document.createElement('div');el.className='log-line';el.textContent=text;$('#combatLog').prepend(el);setTimeout(()=>el.remove(),5200)}
function beep(freq=180,dur=.12,type='sine',vol=.07){if(!settings.sound)return;try{audioCtx??=new AudioContext();if(audioCtx.state==='suspended')audioCtx.resume();const o=audioCtx.createOscillator(),g=audioCtx.createGain();o.type=type;o.frequency.value=freq;g.gain.setValueAtTime(vol,audioCtx.currentTime);g.gain.exponentialRampToValueAtTime(.001,audioCtx.currentTime+dur);o.connect(g).connect(audioCtx.destination);o.start();o.stop(audioCtx.currentTime+dur)}catch{}}
function vibrate(pattern=35){if(settings.vibration&&navigator.vibrate)navigator.vibrate(pattern)}
function now(){return Date.now()+serverOffset}
function randomCode(){const chars='ABCDEFGHJKLMNPQRSTUVWXYZ23456789',v=new Uint8Array(6);crypto.getRandomValues(v);return [...v].map(x=>chars[x%chars.length]).join('')}
function cleanName(){nickname=$('#nickname').value.trim().slice(0,16)||'Гравець';$('#nickname').value=nickname;localStorage.setItem('ta-classic-name',nickname);return nickname}
function wsEndpoint(){const scheme=location.protocol==='https:'?'wss:':'ws:';return `${scheme}//${location.host}/api/ws`}

function startSolo(level='normal'){
  closeSocket();cleanName();mode='solo';difficulty=level;localPlayer=0;state=createState(Date.now(),[nickname,'BOT RANGER']);state.turnEndsAt=Date.now()+WORLD.turnSeconds*1000;eventCursor=0;aiPlan=null;paused=false;renderAmmo();syncHud();show('game');toast('БІЙ ПОЧАВСЯ!');beep(360,.14,'square');
}
function openMultiplayer(){cleanName();show('multiplayer');probeServer()}
function probeServer(){const dot=$('#serverDot'),text=$('#serverText');dot.style.background='#ffbf49';text.textContent='Перевірка онлайн-сервера…';const test=new WebSocket(`${wsEndpoint()}?mode=join&room=AAAAAA&name=probe&client=probe-${Math.random()}`);let done=false;const finish=(ok)=>{if(done)return;done=true;try{test.close()}catch{};dot.style.background=ok?'#56e48a':'#ff5e67';text.textContent=ok?'Онлайн-сервер готовий':'Сервер відповідає, кімнату створить кнопка нижче'};test.onopen=()=>finish(true);test.onerror=()=>finish(false);setTimeout(()=>finish(false),2500)}
function connectOnline(create,code){
  cleanName();closeSocket(false);mode='online';localPlayer=0;ready=false;roomCode=(code||randomCode()).toUpperCase();$('#lobbyCode').textContent=roomCode;$('#lobbyStatus').textContent='Підключення до сервера…';$('#readyBtn').disabled=true;$('#readyBtn').textContent='Я ГОТОВИЙ';show('lobby');
  const url=new URL(wsEndpoint());url.searchParams.set('mode',create?'create':'join');url.searchParams.set('room',roomCode);url.searchParams.set('name',nickname);url.searchParams.set('client',clientId);
  try{ws=new WebSocket(url);ws.onopen=()=>{$('#lobbyStatus').textContent='З’єднано. Очікуємо другого гравця…';$('#readyBtn').disabled=false;pingAt=Date.now();ws.send(JSON.stringify({type:'ping',t:pingAt}))};ws.onmessage=e=>handleNetwork(JSON.parse(e.data));ws.onclose=e=>{if(mode==='online'){setNetwork(false);if(e.code!==1000){$('#lobbyStatus').textContent='З’єднання втрачено. Перепідключення…';scheduleReconnect(create)}}};ws.onerror=()=>{$('#lobbyStatus').textContent='Помилка з’єднання. Повторюємо…'}}catch{scheduleReconnect(create)}
}
function scheduleReconnect(create){clearTimeout(reconnectTimer);reconnectTimer=setTimeout(()=>{if(mode==='online')connectOnline(create,roomCode)},1800)}
function closeSocket(reset=true){clearTimeout(reconnectTimer);reconnectTimer=null;if(ws){try{ws.onclose=null;ws.close(1000,'leave')}catch{}ws=null}if(reset){roomCode='';roomInfo=null;ready=false}}
function sendNet(data){if(ws?.readyState===WebSocket.OPEN)ws.send(JSON.stringify(data))}
function handleNetwork(msg){
  if(msg.serverNow){lastServerNow=msg.serverNow;serverOffset=msg.serverNow-Date.now()}
  if(msg.type==='error'){toast(msg.message||'Помилка кімнати');$('#lobbyStatus').textContent=msg.message||'Помилка';return}
  if(msg.type==='welcome'){roomCode=msg.code;localPlayer=msg.player;$('#lobbyCode').textContent=roomCode;roomInfo=msg.room;renderRoom();if(msg.state){state=msg.state;startOnlineGame()}return}
  if(msg.type==='room'){roomInfo=msg;renderRoom();return}
  if(msg.type==='started'){state=msg.state;lastRevision=-1;startOnlineGame();return}
  if(msg.type==='snapshot'){if(msg.revision<=lastRevision)return;lastRevision=msg.revision;const wasTurn=state?.turn,wasPhase=state?.phase;state=msg.state;if(wasTurn!==state.turn||wasPhase!==state.phase)renderAmmo();handleEvents();syncHud();return}
  if(msg.type==='rejected'){toast(msg.reason||'Дію відхилено');return}
  if(msg.type==='pong'){ping=Math.max(0,Date.now()-msg.t);return}
}
function renderRoom(){if(!roomInfo)return;const names=roomInfo.names||[],r=roomInfo.ready||[],c=roomInfo.connected||[];$('#hostName').textContent=names[0]||'Очікування…';$('#guestName').textContent=names[1]||'Очікування…';$('#hostState').textContent=r[0]?'ГОТОВИЙ':c[0]?'НЕ ГОТОВИЙ':'НЕМАЄ';$('#guestState').textContent=r[1]?'ГОТОВИЙ':c[1]?'НЕ ГОТОВИЙ':'НЕМАЄ';$('#readyBtn').disabled=!c[0]||!c[1]||!!roomInfo.started;$('#lobbyStatus').textContent=roomInfo.started?'Матч уже запущено':c[0]&&c[1]?'Обидва гравці в кімнаті':'Очікуємо суперника…'}
function setNetwork(ok){$('#networkLabel').textContent=mode==='solo'?'SOLO':ok?`ONLINE ${ping?ping+'ms':''}`:'RECONNECT';$('#networkLabel').style.color=ok||mode==='solo'?'#64ef93':'#ffb84a'}
function startOnlineGame(){mode='online';paused=false;eventCursor=state?.events?.length||0;renderAmmo();syncHud();show('game');toast('ОНЛАЙН-БІЙ ПОЧАВСЯ!')}

function renderGarage(){const tanks=[['CLASSIC','#4e99ef','Стартовий танк'],['NEON','#35d9bc','Швидкий стиль'],['TIGER','#f69f2d','Важкий стиль']];const box=$('#tankCards');box.innerHTML='';tanks.forEach((t,i)=>{const b=document.createElement('button');b.className=`tank-card-choice ${settings.tank===i?'selected':''}`;b.style.setProperty('--tank',t[1]);b.innerHTML=`<div class="tank-preview"></div><b>${t[0]}</b><small>${t[2]}</small>`;b.onclick=()=>{settings.tank=i;saveSettings();renderGarage();beep(420,.08)};box.append(b)})}
function renderAmmo(){const bar=$('#ammoBar');bar.innerHTML='';if(!state)return;const t=state.tanks[localPlayer];for(const id of AMMO_ORDER){const a=AMMO[id],n=t.ammo[id];const b=document.createElement('button');b.className=`ammo ${t.selected===id?'selected':''}`;b.title=a.desc;b.disabled=Number.isFinite(n)&&n<=0;b.innerHTML=`<span class="icon">${a.icon}</span><span><b>${a.name}</b><small>${a.damage<0?'лікування':a.damage+' шк.'}</small></span><span class="count">${Number.isFinite(n)?'×'+n:'∞'}</span>`;b.onclick=()=>sendAction({type:'ammo',id});bar.append(b)}}
function sendAction(action){if(!state||paused)return;if(mode==='online'){sendNet({type:'action',action});if(action.type==='aim'){state.tanks[localPlayer].angle=action.angle;state.tanks[localPlayer].power=action.power}else if(action.type==='ammo'){state.tanks[localPlayer].selected=action.id;renderAmmo()}return}if(applyAction(state,localPlayer,action)){if(action.type==='ammo')renderAmmo()}}

function handleEvents(){if(!state?.events)return;while(eventCursor<state.events.length){const e=state.events[eventCursor++];if(e.type==='fire'){beep(125,.18,'sawtooth',.12);vibrate(45);log(`${state.tanks[e.player].name}: ${AMMO[e.ammo]?.name||''}`)}else if(e.type==='explode'){beep(58,.35,'square',.14);vibrate([45,25,80]);log('💥 ВИБУХ')}else if(e.type==='loot'){toast(`🎁 ${e.loot}`);log(`АІРДРОП: ${e.loot}`);beep(650,.2)}else if(e.type==='turn'){toast(e.player===localPlayer?'ВАШ ХІД!':'ХІД СУПЕРНИКА');renderAmmo()}else if(e.type==='plane')log('🛩️ АІРДРОП НАБЛИЖАЄТЬСЯ');else if(e.type==='heal')toast(`+${e.amount} HP`);else if(e.type==='burn')log(`🔥 -${e.amount} HP`)}}
function syncHud(){if(!state)return;const[a,b]=state.tanks;$('#p1Name').textContent=a.name;$('#p2Name').textContent=b.name;$('#p1HpText').textContent=`${Math.ceil(a.hp)} HP${a.shield?` +${Math.ceil(a.shield)}🛡`:''}`;$('#p2HpText').textContent=`${Math.ceil(b.hp)} HP${b.shield?` +${Math.ceil(b.shield)}🛡`:''}`;$('#p1Hp').style.width=`${Math.max(0,a.hp)}%`;$('#p2Hp').style.width=`${Math.max(0,b.hp)}%`;const own=state.tanks[localPlayer];$('#fuelBar').style.width=`${own.fuel}%`;$('#angle').value=own.angle;$('#power').value=own.power;$('#angleOut').textContent=`${Math.round(own.angle)}°`;$('#powerOut').textContent=`${Math.round(own.power)}%`;$('#windLabel').textContent=`ВІТЕР ${state.wind>0?'→':state.wind<0?'←':'•'} ${Math.abs(state.wind)}`;const mine=state.turn===localPlayer;$('#turnLabel').textContent=state.winner!==null?(state.winner===localPlayer?'ПЕРЕМОГА!':'ПОРАЗКА'):mine?'ВАШ ХІД':'ХІД СУПЕРНИКА';$('#timerLabel').textContent=state.phase==='aim'?Math.max(0,Math.ceil((state.turnEndsAt-now())/1000)):'•';setNetwork(mode==='solo'||ws?.readyState===WebSocket.OPEN);const enabled=mine&&state.phase==='aim'&&state.winner===null&&!paused;$('#fireBtn').disabled=!enabled;$('#angle').disabled=!enabled;$('#power').disabled=!enabled;$('#moveLeft').disabled=!enabled;$('#moveRight').disabled=!enabled}
function update(dt){if(!state||paused)return;if(mode==='solo'){if(state.phase==='aim'&&Date.now()>=state.turnEndsAt)fire(state,state.turn);stepState(state,dt);updateAI()}handleEvents();syncHud();if(mode==='online'&&Date.now()-pingAt>4000){pingAt=Date.now();sendNet({type:'ping',t:pingAt})}if(state.winner!==null&&!$('#pausePanel').classList.contains('shown')){setTimeout(()=>{if(state?.winner!==null){paused=true;$('#pausePanel').classList.remove('hidden');$('#pausePanel').classList.add('shown');$('#pausePanel h2').textContent=state.winner===localPlayer?'🏆 ПЕРЕМОГА':'💥 ПОРАЗКА'}},900)}}
function updateAI(){if(state.turn!==1||state.phase!=='aim'||state.winner!==null){aiPlan=null;return}if(!aiPlan){aiPlan=aiChoose(state,difficulty);aiAt=Date.now()+(difficulty==='hard'?650:difficulty==='easy'?1300:900);if(state.airdrop?.landed){const dir=Math.sign(state.airdrop.x-state.tanks[1].x);for(let i=0;i<12;i++)moveTank(state,1,dir,.08)}}else if(Date.now()>=aiAt){state.tanks[1].angle=aiPlan.angle;state.tanks[1].power=aiPlan.power;selectAmmo(state,1,aiPlan.selected);fire(state,1);aiPlan=null}}

function draw(){const sx=canvas.width/WORLD.w,sy=canvas.height/WORLD.h;ctx.setTransform(sx,0,0,sy,0,0);const sky=ctx.createLinearGradient(0,0,0,WORLD.h);sky.addColorStop(0,'#17153f');sky.addColorStop(.43,'#493d9a');sky.addColorStop(.72,'#a861b1');sky.addColorStop(1,'#f0a95b');ctx.fillStyle=sky;ctx.fillRect(0,0,WORLD.w,WORLD.h);drawStars();drawMoon();drawMountains();if(state){drawTrajectory();drawTerrain();drawFires();drawMines();drawDrop();state.tanks.forEach(drawTank);drawProjectiles();drawWinner()}}
function drawStars(){ctx.fillStyle='#fff';for(let i=0;i<70;i++){const x=(i*197+31)%WORLD.w,y=(i*83+17)%420,r=i%9===0?2.2:1;ctx.globalAlpha=.25+.5*Math.abs(Math.sin(i+performance.now()/1800));ctx.beginPath();ctx.arc(x,y,r,0,Math.PI*2);ctx.fill()}ctx.globalAlpha=1}
function drawMoon(){ctx.fillStyle='#fff0b8';ctx.shadowColor='#fff0a0';ctx.shadowBlur=45;ctx.beginPath();ctx.arc(1390,120,65,0,Math.PI*2);ctx.fill();ctx.shadowBlur=0}
function drawMountains(){ctx.fillStyle='#272860';ctx.beginPath();ctx.moveTo(0,660);for(let x=0;x<=WORLD.w;x+=130)ctx.lineTo(x,520+90*Math.sin(x/180)+35*Math.sin(x/61));ctx.lineTo(WORLD.w,900);ctx.lineTo(0,900);ctx.fill();ctx.fillStyle='#1d204b';ctx.beginPath();ctx.moveTo(0,700);for(let x=0;x<=WORLD.w;x+=100)ctx.lineTo(x,610+58*Math.sin(x/130)+22*Math.sin(x/47));ctx.lineTo(WORLD.w,900);ctx.lineTo(0,900);ctx.fill()}
function drawTerrain(){ctx.fillStyle='#294a35';ctx.beginPath();ctx.moveTo(0,WORLD.h);ctx.lineTo(0,state.terrain[0]);for(let i=1;i<state.terrain.length;i++)ctx.lineTo(i*WORLD.groundStep,state.terrain[i]);ctx.lineTo(WORLD.w,WORLD.h);ctx.closePath();ctx.fill();ctx.strokeStyle='#76b54c';ctx.lineWidth=12;ctx.beginPath();state.terrain.forEach((y,i)=>i?ctx.lineTo(i*WORLD.groundStep,y):ctx.moveTo(0,y));ctx.stroke();ctx.strokeStyle='#acd96c';ctx.lineWidth=3;ctx.stroke()}
function drawTrajectory(){if(!state||state.phase!=='aim'||state.turn!==localPlayer||state.winner!==null)return;const t=state.tanks[localPlayer],pts=simulateTrajectory(state,t,t.selected,230,.045);ctx.fillStyle=settings.contrast?'#ff3cf5':'#fff6a8';ctx.strokeStyle='#17153f';ctx.lineWidth=2;for(let i=0;i<pts.length;i+=2){const p=pts[i],r=Math.max(2,6-i*.018);ctx.beginPath();ctx.arc(p.x,p.y,r,0,Math.PI*2);ctx.fill();ctx.stroke()}}
function rr(x,y,w,h,r){ctx.beginPath();ctx.roundRect(x,y,w,h,r)}
function tankColor(t){if(t.id===1)return'#ef554d';return['#4e99ef','#35d9bc','#f69f2d'][settings.tank]||'#4e99ef'}
function drawTank(t){ctx.save();ctx.translate(t.x,t.y);ctx.rotate(t.rotation||0);if(!t.alive)ctx.globalAlpha=.4;ctx.fillStyle='#101126';rr(-38,3,76,28,13);ctx.fill();ctx.fillStyle=tankColor(t);rr(-31,-13,62,27,9);ctx.fill();ctx.fillStyle=t.id?'#ff9872':'#72d7ff';ctx.beginPath();ctx.arc(0,-16,18,Math.PI,0);ctx.fill();const r=t.angle*Math.PI/180;ctx.strokeStyle='#15142e';ctx.lineWidth=11;ctx.lineCap='round';ctx.beginPath();ctx.moveTo(Math.cos(r)*7,-Math.sin(r)*7);ctx.lineTo(Math.cos(r)*54,-Math.sin(r)*54);ctx.stroke();for(const x of[-25,0,25]){ctx.fillStyle='#070817';ctx.beginPath();ctx.arc(x,20,10,0,Math.PI*2);ctx.fill();ctx.fillStyle='#596078';ctx.beginPath();ctx.arc(x,20,5,0,Math.PI*2);ctx.fill()}if(t.shield>0){ctx.strokeStyle='#6de8ffbb';ctx.lineWidth=5;ctx.beginPath();ctx.arc(0,0,55,0,Math.PI*2);ctx.stroke()}ctx.restore()}
function drawProjectiles(){for(const p of state.projectiles||[]){ctx.fillStyle=p.air?'#ff694f':p.mini?'#ffe45c':'#17121d';ctx.shadowColor='#ffb83e';ctx.shadowBlur=12;ctx.beginPath();ctx.arc(p.x,p.y,p.air?9:p.mini?5:8,0,Math.PI*2);ctx.fill();ctx.shadowBlur=0}}
function drawMines(){for(const m of state.mines||[]){ctx.fillStyle='#202133';ctx.beginPath();ctx.arc(m.x,m.y,13,Math.PI,0);ctx.fill();ctx.fillStyle='#ff3f4c';ctx.fillRect(m.x-2,m.y-17,4,5)}}
function drawFires(){for(const f of state.fires||[]){for(let i=0;i<9;i++){const x=f.x+(i-4)*16,y=terrainY(state,x)-8-Math.abs(Math.sin(performance.now()/170+i))*22;ctx.fillStyle=i%2?'#ff4d20':'#ffd327';ctx.beginPath();ctx.moveTo(x-8,terrainY(state,x));ctx.quadraticCurveTo(x,y-25,x+8,terrainY(state,x));ctx.fill()}}}
function drawDrop(){if(state.plane){ctx.save();ctx.translate(state.plane.x,state.plane.y);if(state.plane.vx<0)ctx.scale(-1,1);ctx.fillStyle='#34385c';ctx.beginPath();ctx.moveTo(-65,0);ctx.lineTo(35,-12);ctx.lineTo(70,0);ctx.lineTo(35,12);ctx.closePath();ctx.fill();ctx.fillStyle='#dbe6ef';ctx.fillRect(-8,-27,33,54);ctx.restore()}if(state.airdrop){const d=state.airdrop;if(!d.landed){ctx.strokeStyle='#fff';ctx.lineWidth=4;ctx.beginPath();ctx.arc(d.x,d.y-32,38,Math.PI,0);ctx.stroke();ctx.beginPath();ctx.moveTo(d.x-38,d.y-32);ctx.lineTo(d.x-15,d.y);ctx.moveTo(d.x+38,d.y-32);ctx.lineTo(d.x+15,d.y);ctx.stroke()}ctx.fillStyle='#f6a82b';ctx.fillRect(d.x-20,d.y-18,40,36);ctx.strokeStyle='#6c3e16';ctx.lineWidth=4;ctx.strokeRect(d.x-20,d.y-18,40,36);ctx.fillStyle='#fff';ctx.font='900 24px Arial';ctx.textAlign='center';ctx.fillText('?',d.x,d.y+9)}}
function drawWinner(){if(state.winner===null)return;ctx.fillStyle='#08091dbb';ctx.fillRect(0,0,WORLD.w,WORLD.h);ctx.textAlign='center';ctx.font='900 95px Arial Black';ctx.fillStyle=state.winner===localPlayer?'#ffe36d':'#ff6465';ctx.strokeStyle='#17153f';ctx.lineWidth=10;ctx.strokeText(state.winner===localPlayer?'ПЕРЕМОГА!':'ПОРАЗКА',WORLD.w/2,WORLD.h/2);ctx.fillText(state.winner===localPlayer?'ПЕРЕМОГА!':'ПОРАЗКА',WORLD.w/2,WORLD.h/2)}
function frame(t){const dt=Math.min(.05,(t-last)/1000);last=t;acc+=dt;while(acc>=1/60){update(1/60);acc-=1/60}draw();requestAnimationFrame(frame)}

function setMove(dir,on){if(on)moveDir=dir;else if(moveDir===dir)moveDir=0}
setInterval(()=>{if(!moveDir||!state||paused)return;const enabled=state.turn===localPlayer&&state.phase==='aim'&&state.winner===null;if(!enabled)return;sendAction({type:'move',dir:moveDir,dt:.09})},90);
function aimChanged(){if(!state)return;const a=Number($('#angle').value),p=Number($('#power').value);$('#angleOut').textContent=`${Math.round(a)}°`;$('#powerOut').textContent=`${Math.round(p)}%`;sendAction({type:'aim',angle:a,power:p})}

$('#playBtn').onclick=()=>show('mode');$('#multiBtn').onclick=openMultiplayer;$('#garageBtn').onclick=()=>{renderGarage();show('garage')};$('#settingsBtn').onclick=()=>show('settings');$('#helpBtn').onclick=()=>$('#helpDialog').showModal();$$('[data-back]').forEach(b=>b.onclick=()=>show(b.dataset.back));$('#easyBtn').onclick=()=>startSolo('easy');$('#normalBtn').onclick=()=>startSolo('normal');$('#hardBtn').onclick=()=>startSolo('hard');$('#createBtn').onclick=()=>connectOnline(true,randomCode());$('#joinBtn').onclick=()=>{const c=$('#roomCode').value.toUpperCase().replace(/[^A-Z0-9]/g,'');if(c.length!==6)return toast('Введіть 6 символів коду');connectOnline(false,c)};$('#roomCode').oninput=e=>e.target.value=e.target.value.toUpperCase().replace(/[^A-Z0-9]/g,'');$('#copyCodeBtn').onclick=async()=>{await navigator.clipboard?.writeText(roomCode);toast('КОД СКОПІЙОВАНО')};$('#readyBtn').onclick=()=>{ready=!ready;sendNet({type:'ready',ready});$('#readyBtn').textContent=ready?'СКАСУВАТИ ГОТОВНІСТЬ':'Я ГОТОВИЙ'};$('#leaveLobbyBtn').onclick=()=>{closeSocket();mode='solo';show('multiplayer')};
$('#angle').oninput=aimChanged;$('#power').oninput=aimChanged;$('#fireBtn').onclick=()=>sendAction({type:'fire'});for(const [id,dir] of [['moveLeft',-1],['moveRight',1]]){const b=$('#'+id);for(const ev of ['pointerdown','touchstart'])b.addEventListener(ev,e=>{e.preventDefault();setMove(dir,true)},{passive:false});for(const ev of ['pointerup','pointercancel','pointerleave','touchend'])b.addEventListener(ev,e=>{e.preventDefault();setMove(dir,false)},{passive:false})}
$('#pauseBtn').onclick=()=>{paused=true;$('#pausePanel').classList.remove('hidden')};$('#resumeBtn').onclick=()=>{paused=false;$('#pausePanel').classList.add('hidden');$('#pausePanel').classList.remove('shown')};$('#restartBtn').onclick=()=>{if(mode==='solo')startSolo(difficulty);else sendNet({type:'rematch'});$('#pausePanel').classList.add('hidden');$('#pausePanel').classList.remove('shown')};$('#exitBtn').onclick=()=>{closeSocket();mode='solo';state=null;paused=false;$('#pausePanel').classList.add('hidden');$('#pausePanel').classList.remove('shown');show('menu')};
for(const d of $$('dialog'))d.querySelector('.dialog-x')?.addEventListener('click',()=>d.close());
$('#soundToggle').checked=settings.sound;$('#vibrationToggle').checked=settings.vibration;$('#contrastToggle').checked=settings.contrast;$('#motionToggle').checked=settings.reduced;$('#qualitySelect').value=settings.quality;$('#soundToggle').onchange=e=>{settings.sound=e.target.checked;saveSettings()};$('#vibrationToggle').onchange=e=>{settings.vibration=e.target.checked;saveSettings()};$('#contrastToggle').onchange=e=>{settings.contrast=e.target.checked;saveSettings()};$('#motionToggle').onchange=e=>{settings.reduced=e.target.checked;saveSettings()};$('#qualitySelect').onchange=e=>{settings.quality=e.target.value;saveSettings()};
window.addEventListener('keydown',e=>{if(!screens.game.classList.contains('active'))return;if(['ArrowLeft','a','A'].includes(e.key))setMove(-1,true);if(['ArrowRight','d','D'].includes(e.key))setMove(1,true);if(['ArrowUp','w','W'].includes(e.key)){$('#angle').value=Math.min(175,Number($('#angle').value)+2);aimChanged()}if(['ArrowDown','s','S'].includes(e.key)){$('#angle').value=Math.max(5,Number($('#angle').value)-2);aimChanged()}if(e.code==='Space'){e.preventDefault();sendAction({type:'fire'})}});window.addEventListener('keyup',e=>{if(['ArrowLeft','a','A'].includes(e.key))setMove(-1,false);if(['ArrowRight','d','D'].includes(e.key))setMove(1,false)});window.addEventListener('beforeunload',()=>closeSocket());
if('serviceWorker'in navigator)navigator.serviceWorker.register('/sw.js').catch(()=>{});saveSettings();renderGarage();requestAnimationFrame(frame);
